### PR TITLE
[IMP] Add widget in python_code field for coding directly in view

### PR DESCRIPTION
**Pull request by sla-subteno-it**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please change module version number.

**Comment by sla-subteno-it** [comment]
Version changed.

Thanks

**Review by pedrobaeza — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Great!

**Review by Garamotte — APPROVED** [review]

**Review by lasley — APPROVED** [review]

**Comment by lasley** [comment]
Thanks @alnslang

**Pull request merged**
