### PR TITLE
[13.0][FIX] stock_barcodes: Not pending moves when origin pending moves is stock move lines

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT41789

ping @carlosdauden @chienandalu

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please fw-port all these patches to upper versions.

**Comment by sergio-teruel** [comment]
Thanks!

FW-port to 14 (TT41824) and 15 (TT41823) planned!

**Pull request merged**
