### PR TITLE
update travis config

### PR DESCRIPTION
**Pull request by gurneyalex**
use latest standards

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools

missing --depth 1

**Comment by StefanRijnhart** [comment]
@yvaucher maybe we can leave the depth parameter for a later fix? :+1: on my part.

**Comment by pedrobaeza** [comment]
Rebase should be done. Please add also Transifex.

**Comment by StefanRijnhart** [comment]
Sorry I missed that

**Comment by yvaucher** [comment]
Superseeded by #18

**Pull request closed without merging**
