### PR TITLE
[10.0][FIX] travis.yml

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Travis postgres fix

cc ~ @Eficent

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
travis now works, error is outside of the scope of this PR

**Comment by pedrobaeza** [comment]
Please take the occasion to remove TRANSIFEX stuff and isolated build

**Comment by LoisRForgeFlow** [comment]
ups, cancelling the merge

**Review by pedrobaeza — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza travis error is now in stock_scanner itself, what do we do? a manual merge?

**Comment by pedrobaeza** [comment]
We should fix it. In this case, it's not very complicated and it's due to a change in the logger: just use `mute_logger` for silencing the ERROR in the log, but still raising the exception of the test. Do yo know how to use it?

**Comment by LoisRForgeFlow** [comment]
yes, a decorator in tests, but what should we mute? I don't see the relation, it is a recursive data error.

**Comment by pedrobaeza** [comment]
The problem is that the Travis "crawler" see the line with `ERROR` and thinks that it's not OK, but it's just the error that is provoked and detected by the test, so it's the expected behavior. We have to mute `openerp_test odoo.model`, as the line is:
```
2019-10-21 15:44:12,218 6013 ERROR openerp_test odoo.models: Exception while validating constraint
```

**Comment by LoisRForgeFlow** [comment]
isn't it too much to mute odoo.models??

**Comment by pedrobaeza** [comment]
You can do it for just that specific test or operation. See for example https://github.com/OCA/margin-analysis/blob/cc73f9d63ca8c62837a85df1e6e4edea78f39b5f/product_price_history/wizard/historic_prices.py#L41

**Comment by LoisRForgeFlow** [comment]
Ok, thanks for the insights!

**Comment by pedrobaeza** [comment]
Uhm, it seems it doesn't like it at `with level`... Try mutting the test method

**Comment by LoisRForgeFlow** [comment]
let's see now.

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Agh, I don't understand... I think the problem is the logger route, that is not that simple one... @etobella you had to do this in the past. Do you remember how?

**Comment by LoisRForgeFlow** [comment]
Somotime today we'll get it merged I'm sure :rofl: :rofl: 

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Bravo!

**Pull request merged**
