### PR TITLE
10.0 [MIG] stock_scanner_receipt

### PR DESCRIPTION
**Pull request by misern2**
Standard Migration.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Check the runbot warning:
```
2018-06-12 14:42:10,755 180 WARNING openerp_test odoo.addons.base.ir.ir_model: Creating the ir.model.data scanner_scenario_stock in module stock_scanner instead of stock_scanner_receipt.
```

**Comment by misern2** [comment]
@pedrobaeza the warning is because the data item "Stock" is the parent menu  and should be  shared by all stock_scanner_XXX modules.

That's the reason why it is created in the stock_scanner modules.

**Comment by pedrobaeza** [comment]
Agreed talking directly about putting the menu on the parent module: stock_scanner

**Comment by misern2** [comment]
@pedrobaeza please change the milestone. it's 10.0

**Comment by pedrobaeza** [comment]
It seems there's an incorrect rebase

**Comment by misern2** [comment]
@pedrobaeza Could you please check if it's ok now ?

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@rousseldenis do you agree to merge this?

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@pedrobaeza Done.
FYI could you review this https://github.com/odoo/enterprise/pull/3032 and https://github.com/odoo/enterprise/pull/3031 ?

I faced errors that are not relevant when entering wrong password in sentinel config (with these fixes the real error is raised 'Wrong ID or password').

**Comment by pedrobaeza** [comment]
@rousseldenis sorry, we are not using enterprise modules, so I can't help on that.

**Comment by rousseldenis** [comment]
@pedrobaeza Ok, no problem. As I know you are on Odoo repo often, I wanted to have your advises. :smile:

**Comment by pedrobaeza** [comment]
Yes, I'm on the open source part :wink:

I can say that as something enterprise, you should open an OPW ticket at odoo.com/help, and they should attend the ticket in 2 weeks maximum.

**Pull request merged**
