### PR TITLE
[13.0][IMP] stock_barcodes: Allow get lots automatically depends on removal strategy for picking operations

### PR DESCRIPTION
**Pull request by chienandalu**
Forward of

- [x] #363 

cc @Tecnativa TT34949

please check @sergio-teruel @carlosdauden as your #348 PR could be affected.

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]
This behavior is not implemented in https://github.com/OCA/stock-logistics-barcode/pull/348

**Comment by chienandalu** [comment]
Yes, I meant that you should keep in mind to rebase if necessary to avoid merge conflicts once this is merged

**Comment by pedrobaeza** [comment]
@carlosdauden please give your blessing for merging this

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
