### PR TITLE
[16.0] MIG barcodes_generator_package (from 14.0)

### PR DESCRIPTION
**Pull request by legalsylvain**
product_packaging_sequence_generation

### CODE REVIEW

**Comment by PaulGoubert** [comment]
Functional review OK.  Thank you Sylvain.

**Review by PaulGoubert — APPROVED** [review]

**Review by bealdav — APPROVED** [review]
LGTM

**Comment by legalsylvain** [comment]
Hi maintainers. This PR is ready to merge since 2 monthes. could you merge it ?

**Pull request merged**
