### PR TITLE
[16.0][IMP] stock_barcodes: Allow scan barcode camera

### PR DESCRIPTION
**Pull request by edescalona**
The option to scan barcodes with the camera has been added.

### CODE REVIEW

**Review by pedrobaeza — DISMISSED** [review]
You have to clean the PR, removing unneeded changes in README, readme folder, extra spaces or empty lines.

**Comment by edescalona** [comment]
Hi @pedrobaeza , I've already made some changes, please let me know when you can, thanks

**Comment by pedrobaeza** [comment]
OK, thanks, I remove my "Requested changes", but I'm not able to review further for now.

**Comment by edescalona** [comment]
> OK, thanks, I remove my "Requested changes", but I'm not able to review further for now.

**Comment by edescalona** [comment]
Ok @pedrobaeza , thank you very much for your collaboration.

**Pull request closed without merging**
