### PR TITLE
[14.0] [mig] stock_barcodes

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by fshah-initos** [comment]
@sergio-teruel Can you please review this PR?

**Comment by sergio-teruel** [comment]
Hi @fshah-initos Thanks for the migration...
We are doing many improbements on v13. Can you wait until we do the PR?

**Comment by fshah-initos** [comment]
Hi @sergio-teruel please do let me know once the improvements are done in v13.
Thank you!

**Comment by fshah-initos** [comment]
Is there any update ?

**Comment by sergio-teruel** [comment]
Hi @fshah-initos I have not done the PR yet because it is not finished, documentation, tests and some feedback are missing...
But you can take a look in this branch https://github.com/Tecnativa/stock-logistics-barcode/tree/13.0-IMP-stock_barcodes-new-improvements
Now you can set a guided mode by picking operation, in this mode the app guides user about what he has to do...

**Comment by fshah-initos** [comment]
Okay let us know once it is done

**Comment by fshah-initos** [comment]
Hi @sergio-teruel 
Is the improvements in v13 completed?

**Comment by fshah-initos** [comment]
Hi @sergio-teruel 
Is there any update?

**Comment by fshah-initos** [comment]
Hi @sergio-teruel
Is there any update?

**Comment by fshah-initos** [comment]
Hi @sergio-teruel
Is there any update?

**Comment by hkapatel-initos** [comment]
Hi, @sergio-teruel please do let me know once the all checks are pass in v13 PR. #348
Thank you!

**Review by MiquelRForgeFlow — APPROVED** [review]
> We are doing many improbements on v13. Can you wait until we do the PR?

@sergio-teruel as the v13 improvement PR seems it's going to take long time, I think it would be better to approve and merge this, and later, when the other PR is merged, then forward port the improvement. Ok?

**Comment by sergio-teruel** [comment]
OK @MiquelRForgeFlow

**Comment by hkapatel-initos** [comment]
@sergio-teruel Can you please review this PR?

**Review by DavidBForgeFlow — APPROVED** [review]
LGTM

**Comment by hkapatel-initos** [comment]
Hello maintainers,
it would be nice if you try to merge it.

**Comment by hkapatel-initos** [comment]
Hello maintainers,
it would be nice if you try to merge it.

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
This is quite behind the v13, see https://github.com/OCA/stock-logistics-barcode/pull/330/commits vs https://github.com/OCA/stock-logistics-barcode/commits/13.0/stock_barcodes.

We should include all the commits already in the 13.0 branch.

**Comment by rousseldenis** [comment]
@fshah-initos Could you include those commits :

image

**Comment by hkapatel-initos** [comment]
> This is quite behind the v13, see https://github.com/OCA/stock-logistics-barcode/pull/330/commits vs https://github.com/OCA/stock-logistics-barcode/commits/13.0/stock_barcodes.
> 
> We should include all the commits already in the 13.0 branch.

Done, I have added all the commits now you can merge it.

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks!

**Pull request merged**
