### PR TITLE
[15.0][MIG] stock_barcodes_gs1: Migration to version 15.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT38340

@chienandalu  @CarlosRoca13

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]
Code LGTM

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you please squash administrative commits with the main one as stated in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate ?

**Comment by sergio-teruel** [comment]
Clean done

**Pull request merged**
