### PR TITLE
Separated Lint tests

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by foutoucour** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by tafaRU** [comment]
LGTM
Just out of curiosity, could anyone please explain the reason for having these lines?

```
 services:
   - postgresql
```

**Comment by yvaucher** [comment]
@tafaRU I think we can remove it. It hasn't been cleaned yet.

**Comment by tafaRU** [comment]
@yvaucher if you like I can prepare a PR to remove it, let me know!

**Comment by yvaucher** [comment]
@tafaRU done

**Comment by tafaRU** [comment]
@yvaucher thanks, once green I'll merge it.

**Pull request merged**
