### PR TITLE
[10.0] MIG mobile_app_inventory

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
For me, that version is now ready for production use on v10.

**Comment by legalsylvain** [comment]
Thanks for this work. 

The current PR is based on the V8 PR that is still WIP in my opinion. 
I think we should wait for the resolution of the 8.0 PR problems. (specially regarding some points mentionned here : https://github.com/OCA/stock-logistics-barcode/pull/118#issuecomment-360452692)

kind regards.

**Comment by mcassuto** [comment]
@alexis-via great work !
Quick question, in a multi-location setup, how do we change the inventoried location ?
in my tests, I am unable to change it, neither by scanning the location nor using the location button

**Review by gurneyalex — APPROVED** [review]

**Review by legalsylvain — CHANGES_REQUESTED** [review]
This PR is based on a V8 WIP branch.
It Should include latest improvment available #118.
 
regards.

**Comment by legalsylvain** [comment]
Hi. thanks for this work ! 

t seems you cherry picked the bad branch. seems commits are commit from #114 that has been closed in favor of the merged one #118.
-> so the history is not very clean (a lot of WIP commit). --> not a big deal.
-> there are some features left, like this [commit](https://github.com/OCA/stock-logistics-barcode/pull/118/commits/da974c2b8ec996600c4b9d67591fcb9de711d995). --> more a problem.

what do you think ? Could you apply your patches on the V8 version ?

**Comment by legalsylvain** [comment]
Hi @alexis-via I need this module for Version 10.0 do you want I finish this work, or did you planned to do it ?

regards.

**Comment by alexis-via** [comment]
@legalsylvain  I don't plan to work again on this. Feel free to propose a better port to v10 if you have time to do it.

**Comment by mcassuto** [comment]
@legalsylvain we did completed this work.
Please let us know what is best for you : complete the work from Alex or review & test our version.

Thanks

**Comment by legalsylvain** [comment]
Hi @mcassuto did you based your work on the right branch ? If yes, please propose a PR and I'll review it.

regards.

**Comment by abondis** [comment]
Hi @legalsylvain we started from the code in this PR in march 2018. So from my understanding our code is probably missing features from #118 
I started trying to cherry pick #118, I'll try to push things soon.

**Comment by abondis** [comment]
Hi there, we created a MR for the version we did and use for v10.0 and v11.0 in #174 and #175 

As stated before, it is based on the work already done by @alexis-via before the #118 information.

Since it's been a long time ago, it is hard to make sense of what is to keep and whatnot, and trying to cherry-pick v8.0's version just gave me a module in a broken state, hence why the two new PR.

**Pull request closed without merging**
