### PR TITLE
[14.0] [MIG] stock_barcodes_gs1

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Review by BernatPForgeFlow — APPROVED** [review]
LG!

**Comment by LoisRForgeFlow** [comment]
@JasminSForgeFlow Seems that the tests are failing, could you check?

**Comment by JasminSForgeFlow** [comment]
Add Test failed fix https://github.com/OCA/stock-logistics-barcode/pull/392

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally

**Pull request merged**
