### PR TITLE
[16.0][IMP] product_packaging_multi_barcode: remove packaging_id of product.barcode on product form view

### PR DESCRIPTION
**Pull request by QuocDuong1306**
Depend on:
- https://github.com/OCA/stock-logistics-barcode/pull/563

Now users can not create a new barcode including packaging on `General Information` tab because it will raise [this error](https://github.com/OCA/stock-logistics-barcode/blob/650e410f04e881bd506bc1940a699a25709eed98/product_packaging_multi_barcode/models/product_barcode.py#L35) (in PR above). So I remove the view to avoid confusion.

### CODE REVIEW

**Review by santostelmo — APPROVED** [review]

**Review by cyrilmanuel — APPROVED** [review]

**Comment by cyrilmanuel** [comment]
hii @pedrobaeza , can you merge this PR please ?

**Comment by pedrobaeza** [comment]
It says it depends on https://github.com/OCA/stock-logistics-barcode/pull/563

**Comment by cyrilmanuel** [comment]
Hi @pedrobaeza  the pr https://github.com/OCA/stock-logistics-barcode/pull/563 is merged, can you merge this one ? 

thanks a lot

**Comment by pedrobaeza** [comment]
There are conflicts right now.

**Comment by QuocDuong1306** [comment]
Hello @pedrobaeza , the PR is updated, could you have a look?

**Comment by pedrobaeza** [comment]
Well, I don't know the module, but I merge based on the reviews:

/ocabot merge minor

**Pull request merged**
