### PR TITLE
[9.0][FIX] barcodes_generator_product: Propagate barcode rule to all product variants.

### PR DESCRIPTION
**Pull request by sergio-teruel**
If change or when create a product with variants the rule not is propagted to all variants.
cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
One thing I don't get: the field is only defined at template level. Why do you need to propagate it then?

**Comment by sergio-teruel** [comment]
@pedrobaeza Mhuuu but product_product inherits from barcode_mix_in so barcode_rule is in product_product too.

**Comment by pedrobaeza** [comment]
OK, maybe the fix should be to remove that inheritance. Anyway, you should propagate always the rule, having one variant (default) or having several, isn't it?

**Review by lasley — CHANGES_REQUESTED** [review]
IMO there should be an option to opt-in for this functionality. I have a few use cases where I am also barcoding the variants, which would conflict with this.

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Agree with @lasley. variants has differents barcodes. This feature you introduces is breaking Odoo design, that allow a distinct barcode per variant.
I think that if you need this feature, you'll have to create a new extra module for that.

**Comment by legalsylvain** [comment]
Well, the community doesn't seem to be agree with that design. I close this PR. Feel free to reopen it if design changed.

kind regards.

**Pull request closed without merging**
