### PR TITLE
Correctly use import of addons product

### PR DESCRIPTION
**Pull request by mdietrichc2c**
During the PEP8 validation, the import was renamed from 'product' to 'addon_product', but the call added a layer; this creates an issue "no module called 'product'" when the function _check_ean_key was called.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I prefer to put: `from openerp.addons.product.product import check_ean`, which is clearer.

**Comment by mdietrichc2c** [comment]
@pedrobaeza I actually think addon_product is more readable, as you definitely know you're calling the method from addons, instead of a local one, just by reading _check_ean_key().
@gurneyalex , do you have a preference?

**Comment by pedrobaeza** [comment]
OK, I have no strong opinion about this, but in general, I don't like renaming nothing

**Comment by lepistone** [comment]
I also slightly prefer the direct import without renaming like @pedrobaeza suggests, but It is a detail for me and I :+1: in any case once green. Thanks!

**Comment by nbessi** [comment]
:+1:  for me too

**Comment by nbessi** [comment]
I will fix the flake8 lint stuff now

**Comment by nbessi** [comment]
It is green we can merge now

**Comment by mdietrichc2c** [comment]
:+1: thanks @nbessi

**Comment by jgrandguillaume** [comment]
:+1:

**Pull request merged**
