### PR TITLE
[15.0][IMP] stock_picking_product_barcode_report: Use better the space defined by the image

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT46456

### CODE REVIEW

**Comment by rousseldenis** [comment]
@CarlosRoca13 still draft ?

**Comment by CarlosRoca13** [comment]
No, sorry it is ready

**Comment by CarlosRoca13** [comment]
ping @sergio-teruel @carlosdauden

**Review by sergio-teruel — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Comment by CarlosRoca13** [comment]
ping @pedrobaeza

**Pull request merged**
