### PR TITLE
12.0 mig barcodes generator partner

### PR DESCRIPTION
**Pull request by krunal267**
Hello guys,

I have just signed CLA and sent it to cla@odoo-community.org. Please have look at my PR.

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @krunal267. Thanks for porting this module.

code review. LGTM. 

Just one thing : could you adopt new OCA convention, regarding description. It means splitting description file into many files in the readme folder. ref : 

https://github.com/OCA/maintainer-tools/tree/master/template/module/readme

Thanks !

**Comment by krunal267** [comment]
Hi @legalsylvain 

Thanks for reviewing, I will do the same. :)

**Comment by krunal267** [comment]
Hi @legalsylvain 

I pushed the changes, but ci/runbot check is failed, can you pl. guide me what went wrong?

**Comment by legalsylvain** [comment]
you removed the point_of_sale dependency, that is required I guess ;-)

reverting https://github.com/OCA/stock-logistics-barcode/pull/244/commits/f39cdda92ad4bcf778d5b31a648e7c3a0f124cc9 should fix the problem.

**Comment by krunal267** [comment]
Hi @legalsylvain 

I think all is good now. I added 'client' type in barcode rule which is there in point_of_sale, due that I think the check was failing, so I just added in this module and it's working fine now.

**Comment by legalsylvain** [comment]
Hi @krunal267. Are you sure it will be compatible with the Point of sale module. I mean, calling two times the selection_add with the same key value will works ? (just a question. Don't know exactly).

regards.

**Comment by krunal267** [comment]
I guess ci/runbot check was failing due to demo data of barcode rule was not getting created as it is trying to create barcode rule with type 'client'.

**Comment by krunal267** [comment]
Hi @legalsylvain 
Yes, I had the same doubt, so I tested with Point of sale module and it's working perfectly fine, no issues.

**Review by legalsylvain — APPROVED** [review]
OK. so let's go merging this PR. Thanks for your contribution ! 

/ocabot merge

**Comment by krunal267** [comment]
Okay, Thanks @legalsylvain

**Comment by pedrobaeza** [comment]
@sbidoul why the bot hasn't detected this pylint error:

https://travis-ci.org/OCA/stock-logistics-barcode/jobs/643923263#L333 ?

**Comment by pedrobaeza** [comment]
Fixed in f7ab99d42c5a2a2dcf915c95cf1be1fe6328a35a

**Comment by sbidoul** [comment]
Ther merge commit was green: https://travis-ci.org/OCA/stock-logistics-barcode/builds/643860353?utm_source=github_status&utm_medium=notification

**Comment by pedrobaeza** [comment]
But wasn't the README generated inside that commit? Maybe the checks are not the same there than in the main branch?

**Comment by sbidoul** [comment]
Ah I see. The README generator runs after testing the merge commit.
It comes from here: https://github.com/OCA/oca-github-bot/commit/d5791fdd05b922126b138f8b514ab9d91093b05d

And for some reason the readme generator did not detect the error. I created https://github.com/OCA/maintainer-tools/issues/441 to track this.

**Pull request merged**
