### PR TITLE
[16.0][MIG] base_gs1_barcode

### PR DESCRIPTION
**Pull request by tewtawat**
Standard Migration

### CODE REVIEW

**Comment by rousseldenis** [comment]
/ocabot migration base_gs1_barcode

@tewtawat @StefanRijnhart @sergio-teruel @gurneyalex @fshah-initos @JasminSForgeFlow Have you seen that in v15, there is a module for gs1 (barcodes_gs1_nomenclature).

Shouldn't this be updated accordingly ?

**Comment by simahawk** [comment]
> Shouldn't this be updated accordingly ?

I agree. 

These days we are checking `barcodes_gs1_nomenclature` on v15 and we'll probably backport it to v14 (where we need it).

Despite I don't like that much its code (surprise surprise :stuck_out_tongue_closed_eyes: ) I don't see why we should carry on `base_gs1_barcode`.
Honest question: what's the added value?

**Comment by sergio-teruel** [comment]
Yes I know, I have yet to take a look at it and see if we can remove the current base_gs1_barcode module

**Comment by edescalona** [comment]
Hi @sergio-teruel , could you please tell me if it was possible to replace the base_gs1_barcode module with barcodes_gs1_nomenclature? Thank you for your contribution.

**Comment by sergio-teruel** [comment]
Yes... already done in 16.0

**Comment by edescalona** [comment]
Thank you @sergio-teruel  for your response

**Pull request closed without merging**
