### PR TITLE
[12.0][MIG] stock_scanner_web

### PR DESCRIPTION
**Pull request by eantones**
Migration to 12.0

Starting from https://github.com/OCA/stock-logistics-barcode/pull/95

@angelmoya @LoisRForgeFlow @realsaiko @lmignon  @MiquelRForgeFlow  @rousseldenis   can you review it please? 

Thanks!
:-)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
FYI we developed https://github.com/OCA/stock-logistics-barcode/tree/12.0/stock_barcodes as a more convenient solution for us.

**Comment by eantones** [comment]
@pedrobaeza yes, I know that module and I already try it, It's really good but I need the flexibility of `stock_scanner` in order to interact even with the manufacture module.
Thank you anyway :-)

**Comment by pedrobaeza** [comment]
There's an ongoing `mrp_barcodes` from other contributor...

**Comment by eantones** [comment]
I know, but still, it's not flexible enough
Gracias Pedro :-)

**Comment by pedrobaeza** [comment]
OK, no problem. Both can be here :)

**Comment by eantones** [comment]
@pedrobaeza I have the 11.0 version ready too, it's not exactly the same due to the Phantom_js deprecation, should I propose the PR or wait for how this one goes first?

**Comment by pedrobaeza** [comment]
What you prefer. It's legit to propose it already. The only cons is if someone reviews one of both PR and propose changes, that you may need to spread it in both PRs. That's why I wait for one version to be merged until I start migrating the next.

Take also into account that you need to attract reviewers to this. One possibility is to review other PRs and asking in exchange to review yours.

**Comment by eantones** [comment]
Perfect, thanks!

**Comment by rousseldenis** [comment]
Great! Thanks for this. It has been paused for so long. I'll review it and test it when I have time.

**Comment by rousseldenis** [comment]
@eantones Could you rebase ?

**Comment by eantones** [comment]
@rousseldenis done! :-)

**Pull request closed without merging**
