### PR TITLE
[12.0] stock_barcodes: Allow to add new stock moves to a picking

### PR DESCRIPTION
**Pull request by eLBati**
See https://github.com/OCA/stock-logistics-barcode/issues/224

Based on https://github.com/OCA/stock-logistics-barcode/pull/226

Depends on https://github.com/OCA/stock-logistics-barcode/pull/267

### CODE REVIEW

**Review by mrcast — APPROVED** [review]
Functional test ok for picking in

**Review by mrcast — COMMENTED** [review]
Problem in Picking out
Start barcode reader in Delivery Order
turn on: Manual entry data, Free Insert, New Picking
Reading a barcode I obtain an alert: Destination Location

**Comment by eLBati** [comment]
@mrcast changed, please retry, thanks

**Review by mrcast — APPROVED** [review]
Functional test:
picking in and out with manual entry: OK
picking in and out with free insert: OK

**Pull request closed without merging**
