### PR TITLE
[15.0][MIG] barcodes_generator_abstract

### PR DESCRIPTION
**Pull request by sla-subteno-it**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
/ocabot migration barcodes_generator_abstract

Please check pre-commit. You can install it locally and put it to be run before commiting.

**Comment by sla-subteno-it** [comment]
@pedrobaeza I just fix it. Is-it ok for you ?

**Comment by pedrobaeza** [comment]
Yes, thanks

**Comment by sla-subteno-it** [comment]
@legalsylvain It's ok for you this migration ?

**Comment by CasVissers-360ERP** [comment]
@sla-subteno-it 
Not sure if it's related to the abstract or product generate module but I get an error while opening barcode rules:

```
UncaughtPromiseError
Uncaught Promise > While parsing modifiers for field encoding: for modifier "invisible": Unknown field parent.is_gs1_nomenclature in domain
Error: While parsing modifiers for field encoding: for modifier "invisible": Unknown field parent.is_gs1_nomenclature in domain
    at Class._registerModifiers (https://customer-15-0-staging-3816306.dev.odoo.com/web/assets/1931-caead80/web.assets_backend.min.js:4764:160)
    at Class._renderFieldWidget (https://customer-15-0-staging-3816306.dev.odoo.com/web/assets/1931-caead80/web.assets_backend.min.js:4772:296)
    at Class._renderFieldWidget (https://customer-15-0-staging-3816306.dev.odoo.com/web/assets/1931-caead80/web.assets_backend.min.js:5034:13)
    at Class.prototype.<computed> [as _renderFieldWidget] (https://customer-15-0-staging-3816306.dev.odoo.com/web/assets/1930-72e2ea6/web.assets_common.min.js:4716:488)
    at Class._renderInnerGroupField (https://customer-15-0-staging-3816306.dev.odoo.com/web/assets/1931-caead80/web.assets_backend.min.js:5044:381)
    at https://customer-15-0-staging-3816306.dev.odoo.com/web/assets/1931-caead80/web.assets_backend.min.js:5041:44
    at Array.forEach (<anonymous>)
    at Class._renderInnerGroup (https://customer-15-0-staging-3816306.dev.odoo.com/web/assets/1931-caead80/web.assets_backend.min.js:5038:75)
    at Class._renderTagGroup (https://customer-15-0-staging-3816306.dev.odoo.com/web/assets/1931-caead80/web.assets_backend.min.js:5054:248)
    at Class._renderNode (https://customer-15-0-staging-3816306.dev.odoo.com/web/assets/1931-caead80/web.assets_backend.min.js:5046:244)
```

**Review by legalsylvain — COMMENTED** [review]
Diff review. Lgtm. Could you add me as maintainers in the manifest ?
That field was not existing when I shared that module.
Thanks for porting this module !

**Comment by tewtawat** [comment]
Hi, I need this module as dependency of another one. @sla-subteno-it can you look at this?

**Comment by rousseldenis** [comment]
@sla-subteno-it Could you rebase ?

**Review by chienandalu — CHANGES_REQUESTED** [review]
@sla-subteno-it Rebase so this PR can be finally reviewed

**Comment by rousseldenis** [comment]
Closing this as supersedes by #483

**Pull request closed without merging**
