### PR TITLE
11.0 [MIG] barcode_generator_lot

### PR DESCRIPTION
**Pull request by misern2**
Standard Migration

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by misern2** [comment]
@pedrobaeza Rebase done!

**Review by pedrobaeza — APPROVED** [review]

**Comment by rousseldenis** [comment]
@misern2 Could you fix lint errors ?

**Comment by misern2** [comment]
@rousseldenis done

**Review by rousseldenis — APPROVED** [review]
Code review. Could you please squash your commits?

**Pull request merged**
