### PR TITLE
[12.0][MIG] stock_scanner_web_location_info

### PR DESCRIPTION
**Pull request by eantones**
Migration to 12.0

Starting from https://github.com/OCA/stock-logistics-barcode/pull/95

Related to https://github.com/OCA/stock-logistics-barcode/pull/275

@angelmoya @LoisRForgeFlow @realsaiko @rousseldenis can you review it please? 

Thanks!
:-)

### CODE REVIEW

**Comment by eantones** [comment]
How can I avoid the Runbot dependency error if the parent module is not yet merged? I know that I might have both on the same PR but I'd prefer a cleaner solution.
Thanks in advance

**Comment by rousseldenis** [comment]
> How can I avoid the Runbot dependency error if the parent module is not yet merged? I know that I might have both on the same PR but I'd prefer a cleaner solution.
> Thanks in advance

Hi! Thanks for this. You can add a line with the repo name plus the github link to your branch in the oca_dependencies.txt (to be removed before merge).

e.g.: stock-logistics-barcode https://github.com/nuobit/stock-logistics-barcode 12.0-mig-stock_scanner_web

I think there is a more cleaner option is to use test-requirements.txt (but it has to be enabled on the repo)

**Comment by pedrobaeza** [comment]
I'm afraid that doesn't serve when the repository of the dependency is the same.

**Comment by eantones** [comment]
Ok, so in this case, is it better to put both modules on the same PR?

**Comment by rousseldenis** [comment]
> Ok, so in this case, is it better to put both modules on the same PR?

Or basing your branch on the other one.

**Comment by pedrobaeza** [comment]
You can put this one as WIP and rebase when the other is merged. Several modules in one PR is not advisable and can make the review more difficult.

**Comment by eantones** [comment]
I think I did not understand, if I rebase this branch on the parent one then this PR will have also all the commits from the parent and it will contain two modules which is what we are trying to avoid.
What am I missing?

**Comment by eantones** [comment]
@rousseldenis I rebased this as well, in case you need it :-)

**Pull request closed without merging**
