### PR TITLE
[13.0][IMP] stock_barcodes_gs1: Allow the use of double GS1-128 barcodes

### PR DESCRIPTION
**Pull request by etobella**
Cherry-pick of #297

### CODE REVIEW

**Comment by etobella** [comment]
@sergio-teruel @LoisRForgeFlow

**Review by sergio-teruel — APPROVED** [review]
Waiting green...

**Comment by pedrobaeza** [comment]
Still red

**Comment by etobella** [comment]
:green_apple:

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
