### PR TITLE
[16.0][IMP] stock_barcodes: use trash icons instead of recycle icons in inventory

### PR DESCRIPTION
**Pull request by alexis-via**
BEFORE

stock_barcodes_before

AFTER

stock_barcodes-after

### CODE REVIEW

**Comment by sergio-teruel** [comment]
Well!! I not used this icon because the quant is not really deleted, only set to zero...
Maybe it could be changed..

@carlosdauden, what do you think about it?

**Review by rvalyi — DISMISSED** [review]

**Comment by legalsylvain** [comment]
Agree with alexis, that the current "recycle" icon doesn't make sense.

> Well!! I not used this icon because the quant is not really deleted, only set to zero...

Indeed. In odoo, trash is for deletion.

if the meaning is "reset" something like this icone is maybe more suitable : https://fontawesome.com/v6/icons/rotate-left?f=classic&s=solid

**Comment by alexis-via** [comment]
@sergio-teruel Your remark is true from a technical point of view. My PR proposes to adopt the user's point of view: the user scans something by mistake and wants to cancel : with a trash icon, he removes his scan and then can scan again.

All the users that I trained on stock_barcodes told me that the recycle icon was not intuitive.

**Comment by sergio-teruel** [comment]
hi @alexis-via Ok.. perfect!!

**Review by sergio-teruel — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Comment by carlosdauden** [comment]
Personally I like the icon proposed by @legalsylvain better, but what we all agree on is that the fa-recycle is not appropriate. :wink:

**Comment by pedrobaeza** [comment]
Then switch to the other icon before merging, Alexis.

**Comment by carlosdauden** [comment]
Merge with fa-trash to be closer to the user's approach

**Comment by pedrobaeza** [comment]
OK, I merge as is:

/ocabot merge minor

**Pull request merged**
