### PR TITLE
[17.0][MIG] barcodes_generator_product: Migration to 17.0

### PR DESCRIPTION
**Pull request by niboo-jva**

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi. Thanks for porting ! Could you review and cherry-pick this one ?
https://github.com/OCA/stock-logistics-barcode/pull/592
Thanks !

**Comment by desdelinux** [comment]
Hi @jvandri , test is red

**Comment by rousseldenis** [comment]
@jvandri Do you plan to finish this or do you agree to switch to #620 ?

**Comment by desdelinux** [comment]
> @jvandri Do you plan to finish this or do you agree to switch to #620 ?

@rousseldenis Please close it, the other pr has taken into account the suggestions of this pr

**Review by desdelinux — APPROVED** [review]

**Pull request closed without merging**
