### PR TITLE
[14.0][MIG] product_multi_barcode: migration to 14.0

### PR DESCRIPTION
**Pull request by kevinkhao**
Supersedes #309

### CODE REVIEW

**Comment by kevinkhao** [comment]
Supersedes https://github.com/OCA/stock-logistics-barcode/pull/309

**Comment by kevinkhao** [comment]
@jjscarafia if you could help approve :pray:

**Comment by jjscarafia** [comment]
Hi @kevinkhao 
Can you pleas fix runbot?
It seem you should remove the ["inverse_sudo"](https://github.com/OCA/stock-logistics-barcode/blob/13.0/product_multi_barcode/models/product_product.py#L22). That come from v11 or before but it seems there is a new check in odoo that detects this invalid parameter.

Thanks!

**Review by jjscarafia — APPROVED** [review]
LGTM

**Review by hparfr — APPROVED** [review]
LGTM

**Comment by kevinkhao** [comment]
bot seems stuck, seems there is no commit in https://github.com/OCA/stock-logistics-barcode/commits/14.0

**Comment by pedrobaeza** [comment]
@hparfr the bot didn't merge it. Do you launch it again?

**Comment by hparfr** [comment]
@kevinkhao can you please fix the rst ? 

```sh
************* Module barcodes_generator_abstract
barcodes_generator_abstract/README.rst:143: [E7901(rst-syntax-error), ]  Duplicate implicit target name: "note".
************* Module barcodes_generator_abstract.models.barcode_generate_mixin
barcodes_generator_abstract/models/barcode_generate_mixin.py:9: [W7936(missing-manifest-dependency), ] Missing external dependency "barcode" from manifest. More info: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#external-dependencies

pylint with mandatory checks.............................................Failed
- hook id: pylint
```

https://github.com/OCA/stock-logistics-barcode/runs/3475383597#step:4:126

**Comment by kevinkhao** [comment]
@hpar rebased on fixed 14.0

**Pull request merged**
