### PR TITLE
[15.0][MIG]barcodes_generator_product

### PR DESCRIPTION
**Pull request by manuelregidor**
Depends on https://github.com/OCA/stock-logistics-barcode/pull/483

### CODE REVIEW

**Comment by rousseldenis** [comment]
@manuelregidor Thanks for this. Note that in order to test your PR, you can include your dependency(ies) in a test-requirements.txt file (tests and runboat could run fine).

You can read : https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre @luis-ron

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
