### PR TITLE
11.0 mig barcode generator location

### PR DESCRIPTION
**Pull request by misern2**
Standard migration

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests, but when I merge the dependency for pushing only once.

**Comment by pedrobaeza** [comment]
Please rebase after merging dependency

**Comment by misern2** [comment]
@pedrobaeza Rebase done!

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@misern2 please find another reviewer to this PR

**Review by tbaden — CHANGES_REQUESTED** [review]
conflicting files.

please merge and rebase.

**Comment by rousseldenis** [comment]
@misern2 Do you plan to achieve this ?

**Comment by misern2** [comment]
@rousseldenis @tbaden

**Comment by rousseldenis** [comment]
Could you please squash your last two commits?

Are the files permissions changes normal ?

**Pull request closed without merging**
