### PR TITLE
[IMP] stock_barcodes: Find quant to select the proper location

### PR DESCRIPTION
**Pull request by albariera**
Cherry-pick from 12.0 6b2ee8d

### CODE REVIEW

**Comment by albariera** [comment]
Cherry-pick from 12.0 https://github.com/OCA/stock-logistics-barcode/commit/6b2ee8de6794fb0f0aecf8fd3fe3d404f26cff03

**Review by etobella — APPROVED** [review]
Thanks!!!

**Review by chienandalu — APPROVED** [review]

**Comment by chienandalu** [comment]
ping @sergio-teruel

**Comment by sergio-teruel** [comment]
Please review if this behaviour is covered here 
#348 (https://github.com/OCA/stock-logistics-barcode/pull/348/commits/8bb3d7c22541a4abd72a3c79ca5f792058e4634d)

**Review by andreampiovesana — APPROVED** [review]
merge?

**Comment by chienandalu** [comment]
@sergio-teruel asserted that this feature was being added in #348

**Comment by sergio-teruel** [comment]
This behavior is taken into account here:
https://github.com/Tecnativa/stock-logistics-barcode/blob/acc0ee7227317095caddf0e54c3891a2b4084d36/stock_barcodes/wizard/stock_barcodes_read.py#L207

**Comment by albariera** [comment]
Ok, so I close this PR!

**Pull request closed without merging**
