### PR TITLE
10.0 [MIG] stock_scanner_location_info

### PR DESCRIPTION
**Pull request by misern2**
Standard migration.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by pedrobaeza** [comment]
There is the following warning:
```
2018-06-12 11:27:39,435 180 WARNING openerp_test odoo.addons.base.ir.ir_model: Creating the ir.model.data scanner_scenario_stock in module stock_scanner instead of stock_scanner_location_info.
```

**Comment by pedrobaeza** [comment]
It seems there's an incorrect rebase

**Comment by rousseldenis** [comment]
@OCA/logistics-maintainers This is an old one

**Review by rafaelbn — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@misern2 it seems there's a problem on the rebased branch.

**Comment by rousseldenis** [comment]
@misern2

**Pull request merged**
