### PR TITLE
[ADD][WIP] Change of functionality for automatic generation of bar codes

### PR DESCRIPTION
**Pull request by cramosh**
In this PR the main modification is that the `generate_automate` checkbox is bounded to the rule itself. 
Behaviour before this PR
When you click the automatic checkbox inside a rule it apply to all products in your inventory. It has no sense because:
The checkbox is inside the rule
You can not have two or more product barcode rules in your database

Behaviour after this PR
When you click the automatic checkbox inside a rule, it is bounded to the usage of this rule in the product template, solving the main two problems of the previous behaviour.

In order to keep the old behaviour, a new checkbox `general_rule` is added to put this rule by default when you create a new product. This checkbox can only be checked in one rule with the same `generate_model`.

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
>  You can not have two or more product barcode rules in your database

hi @cramosh. At a first sight, this assertion is wrong. having many product barcode rules is totally valid. see for exemple ``barcode_rule_weight_three_dec`` and ``barcode_rule_price_two_dec`` in odoo data.

**Comment by Mat-moran** [comment]
Hi @legalsylvain ,

`barcode_rule_weight_three_dec` and `barcode_rule_price_two_dec` are modules? we do not find tthem.

Please can you clarify it?

**Comment by legalsylvain** [comment]
@Mat-moran Sorry for not being clear.

``barcode_rule_weight_three_dec`` and ``barcode_rule_price_two_dec`` are xml_ids of barcode rule of products created by odoo.

- https://github.com/odoo/odoo/blob/14.0/addons/point_of_sale/data/default_barcode_patterns.xml#L30
- https://github.com/odoo/odoo/blob/14.0/addons/stock/data/default_barcode_patterns.xml#L4

**Comment by cramosh** [comment]
> > You can not have two or more product barcode rules in your database
> 
> hi @cramosh. At a first sight, this assertion is wrong. having many product barcode rules is totally valid. see for exemple `barcode_rule_weight_three_dec` and `barcode_rule_price_two_dec` in odoo data.

What I mean by not being able to have more than one rule is that odoo does not allow you to create more than one automatic rule for barcodes.

On the other hand, having it marked, what the program does is always use that rule, even though I do not have a different rule selected in the product sheet.

This PR is a propose for solved Issue #401

**Pull request closed without merging**
