### PR TITLE
[14.0][UPD] Copier update + barcodes_generator_abstract fixes

### PR DESCRIPTION
**Pull request by kevinkhao**
* update copier
* fix problem blocking PRs on barcodes_generator_abstract

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please don't remove README, but regenerate it. And why is it redundant?

**Comment by pedrobaeza** [comment]
But again, why is it redundant?

**Comment by kevinkhao** [comment]
All contents of DEVELOP.rst are already included in USAGE.rst, except in USAGE.rst it's a bit corrected and better formatted.

Screenshot from 2021-09-01 09-56-00

For the readme, I removed its contents because pre-commit disapproves redundant "Note" section (because of identical content in DEVELOP/USAGE). I thought the ocabot regenerated it automatically, anyways I regenerated it.

**Comment by pedrobaeza** [comment]
OK, I see. Thanks for the extra info.

Let's fast-track it for solve the problem:

/ocabot merge patch

**Pull request merged**
