### PR TITLE
[11.0] [MIG] stock_scanner_receipt

### PR DESCRIPTION
**Pull request by misern2**
Standard Migration

Depends on #149

### CODE REVIEW

**Comment by rousseldenis** [comment]
@misern2 #149 merged. Could you rebase ?

**Comment by misern2** [comment]
@rousseldenis Can you please  check it if it's ok ?

**Comment by rousseldenis** [comment]
@misern2 I think there is a mess in your commit history. Mixing modules...

**Comment by misern2** [comment]
@rousseldenis Rebase done again. I think it's ok now. I'm not sure how to deal with some git commands  ;-)

**Review by rousseldenis — APPROVED** [review]
Code review. Seems ok.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
