### PR TITLE
[11.0][MIG] barcodes_generator_partner

### PR DESCRIPTION
**Pull request by xavierjimenez**
Migration of the module **barcodes_generator_partner** to version 11.0.

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @xavierjimenez. Thanks for porting this module.

Well, I don't think that removing a space in a readme file, and bumping version make you an author of this module, neither a contributor. Could you remove your reference. 

kind regards.

**Comment by xavierjimenez** [comment]
Hi @legalsylvain, no problem. I've remove the references on both PRs (#142 #143).

Kind regards,

**Review by legalsylvain — APPROVED** [review]
thanks !

**Comment by pedrobaeza** [comment]
Can you please squash together according image:

seleccion_001

**Comment by legalsylvain** [comment]
@pedrobaeza : Could point the OCA rule that says that contributors have to squash all the old commits in all the new PR ?

If this rule is not defined, well, squash the commits in your PR if you want, but please don't ask to the community to do the same.

Regards.

CC : @OCA/board

**Comment by pedrobaeza** [comment]
@legalsylvain I'm not asking you, but other contributor and it's something reasonable for having a good commit history now that we have the opportunity, so please don't intervene here.

**Comment by legalsylvain** [comment]
@pedrobaeza : I'm not agree. The objective of the review is not to ask to contributors to make changes based on personal tastes, but on common rules.

Otherwise, I see some problems : 
-> another reviewer could ask the opposite, because for him, history is important (matter of taste, after all)
-> It slows down the review / merge process
-> contributors  will become discouraged and will contribute less

So please, if you think we *should* squash commits of others, please make an issue on https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md describing in which cases it's required.

For the time being, it seems that there are pro and cons about that point. Ref : https://github.com/OCA/maintainer-tools/issues/248#issuecomment-265999131. CC @lmignon.

In the meantime let's go merging this PR !

**Comment by pedrobaeza** [comment]
@legalsylvain This is not clear the case, as you can see in the commit history that are little mistakes, and the contributor agrees to do it, so again: don't intervene more.

I will respect you and Laurent's PRs, don't worry.

**Comment by xavierjimenez** [comment]
I've cleaned the commit history so now it should be good to merge!

**Pull request merged**
