### PR TITLE
[14.0] [mig] base_gs1_barcode

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by fshah-initos** [comment]
@jimhoefnagels It would be nice if you could add reviews here.

**Review by dsolanki-initos — APPROVED** [review]
LGTM

**Comment by fshah-initos** [comment]
It would be great if we could get the reviews here.

**Comment by fshah-initos** [comment]
It would be great if we could get the reviews here.

**Comment by fshah-initos** [comment]
It would be nice we get the reviews here so that we can merge the PR ASAP.

**Comment by fshah-initos** [comment]
It would be nice we get the reviews here so that we can merge the PR ASAP.

**Comment by fshah-initos** [comment]
@jimhoefnagels It would be ncie if you could add reviews here

**Comment by fshah-initos** [comment]
It would be nice we get the reviews here so that we can merge the PR ASAP.

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
