### PR TITLE
[FIX]Improved record id.

### PR DESCRIPTION
**Pull request by MeetKD**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why this change?

**Comment by MeetKD** [comment]
**view_production_lot_form** record id is used in stock module. To uniquely identify the record id I have changed the id and used **view_barcode_production_lot_form** to differentiate record id.

**Comment by pedrobaeza** [comment]
On contrary, the style guide indicates to put the same ID, as the fully qualified XML-ID is module+ID, so no possible choke. Please check these guidelines: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md

**Comment by MeetKD** [comment]
Okay. Thank you for clarification.

**Pull request closed without merging**
