### PR TITLE
[FIX] Added parent menu Stock  for stock_scanner_XXX modules

### PR DESCRIPTION
**Pull request by misern2**
As commented in pr #146

### CODE REVIEW

**Comment by misern2** [comment]
@pedrobaeza As soon as it is merged I'll update the rest of PR.

Thanks!

**Review by pedrobaeza — APPROVED** [review]
Waiting for CIs for fast-tracking this

**Comment by Garamotte** [comment]
This will create a menu which will be always displayed. Not anyone will want this menu.

Moreover, the active flag is set in the data, and it is not set as noupdate.

**Comment by pedrobaeza** [comment]
Yeah, but it's the only way for avoiding an error in runbot in the rest of the modules, and that menu is not a problem at all. You can't put it non active, or you will have the same problem reactivating it on children menus.

**Comment by Garamotte** [comment]
Maybe we can mimic Odoo's behaviour: If a menu has no child, do not display it on the scanner.

The issue is that always displaying it will be boring for most users when there is no child in this menu. And I think it will crash if someone selects it.

**Comment by pedrobaeza** [comment]
OK, I think that can be feasible. @misern2 do you think you can do it?

**Comment by misern2** [comment]
@pedrobaeza @sylvain-garancher  Finally I think the best approach is to hide the menu option only in SSH client and leave it in  the backend (Odoo) as it is

**Comment by pedrobaeza** [comment]
Do you know why Travis is red?

**Comment by pedrobaeza** [comment]
```
stock_scanner/models/scanner_hardware.py:765:26: E231 missing whitespace after ','
stock_scanner/models/scanner_hardware.py:765:35: E231 missing whitespace after ','
stock_scanner/models/scanner_hardware.py:766:25: E231 missing whitespace after ','
stock_scanner/models/scanner_hardware.py:766:34: E231 missing whitespace after ','
stock_scanner/models/scanner_scenario.py:79:21: E251 unexpected spaces around keyword / parameter equals
```

**Comment by pedrobaeza** [comment]
Merging this as well

**Pull request merged**
