### PR TITLE
[FIX][12.0] stock_barcodes_supplierinfo ignore possible lot scan

### PR DESCRIPTION
**Pull request by sergiocorato**
In case of lot scan, the current function do not find the product with this barcode and return ignoring the scanned barcode.
This PR fix this.

### CODE REVIEW

**Review by eLBati — APPROVED** [review]
LGTM

**Review by kenayagi — APPROVED** [review]
LGTM

**Comment by sergiocorato** [comment]
@OCA/logistics-maintainers can this be merged?

**Pull request merged**
