### PR TITLE
[13.][IMP] stok_barcodes: add html field to track pending products

### PR DESCRIPTION
**Pull request by albariera**
Cherry-pick from #338

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — COMMENTED** [review]
Wouldn't it be more useful to list next detailed operations (stock.move.line), this way you will have proper source/dest location, lot information, etc.

What do you think?

**Comment by albariera** [comment]
@LoisRForgeFlow I agree with you. I have added an option to show detailed pending moves, non-detailed pending moves or both in case it is needed. This is how it looks if both are shown:
image
What do you think?

**Comment by LoisRForgeFlow** [comment]
@albariera It looks good! A couple of comments though:

- In detailed operations can you rename "Initial Demand" by "Reserved"?
- How does it look the list in a phone screen? Can you paste an screenshot of that as well?

Thanks!

**Comment by albariera** [comment]
"Intial Demand" already changed to "Reserved" in detailed operations (at non-detailed it remains as "Demand" if you agree)
Here you have the phone view (with web_responsive installed):
image
Thank you!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM, maybe a kanban view would help to visualice all the information in the table of detailed operations (the table overflows in the right). Anyway that can be a future improvement, thanks for considering my suggestions!

**Comment by sergio-teruel** [comment]
All this is working in this PR https://github.com/OCA/stock-logistics-barcode/pull/348

**Comment by sergio-teruel** [comment]
This commit has caused conflicts in the PR

**Comment by pedrobaeza** [comment]
So should we revert it and continue with your PR?

**Comment by LoisRForgeFlow** [comment]
@sergio-teruel @pedrobaeza Sorry, I thought that one was staled. Feel free to revert it, you are the maintainers of the module.

**Comment by sergio-teruel** [comment]
Yes, please.
This changes we are working on this improvements...

**Comment by pedrobaeza** [comment]
Reverted in #373

**Pull request merged**
