### PR TITLE
[REF] update author name

### PR DESCRIPTION
**Pull request by fmdl**
cc @alnslang

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you explain this change?

**Comment by legalsylvain** [comment]
the company syleam has been recently renamed into subteno-it.

ref : https://www.subteno-it.fr/

**Review by pedrobaeza — APPROVED** [review]
OK then

**Comment by fmdl** [comment]
https://github.com/OCA/stock-logistics-barcode/pull/164

**Pull request closed without merging**
