### PR TITLE
[10.0] multi ean backport form v11.0

### PR DESCRIPTION
**Pull request by flotho**
this PR is a backport of the v11 module.
it probably invalidate this PR : https://github.com/OCA/stock-logistics-barcode/pull/97

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please preserve commit history?

**Comment by flotho** [comment]
Hi @pedrobaeza ,

thanks for the reading. Sorry for the newbie question, what is the procedure to preserve commit history between branches ?
regards

**Comment by pedrobaeza** [comment]
Use https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0, but inverting 10.0 <> 11.0 in the main command

**Comment by rousseldenis** [comment]
@flotho Any news on this ?

**Comment by flotho** [comment]
@rousseldenis , I'm gonna fix this today I hope

**Comment by flotho** [comment]
Another newbie question regarding the preservation of the history.
I'm trying to follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#technical-method-to-migrate-a-module-from-100-to-110-branch and inverting 10.0/11.0 but I still have stange behaviour.
Here is what I've done : 
```
git checkout 10.0
git pull origin 10.0
git checkout -b 10.0-mig-multi-barcode origin/10.0
git format-patch --keep-subject --stdout origin/10.0..origin/11.0 --  product_multi_ean | git am -3 --keep
```
The latest command give me many conflict and don't seems to preserve the 11.0 structure.

What am I doing wrong? 

Thanks for your help

**Comment by flotho** [comment]
My bad, I wasn't working on the correct repo

**Comment by HviorForgeFlow** [comment]
I found an issue on that module, IDK if it is also related with v10. It could be interesting to add it on backport.
https://github.com/OCA/stock-logistics-barcode/pull/180

**Comment by flotho** [comment]
definitively I didn't succeed in the procedure for preserving history.
Does anyone could help me on https://github.com/OCA/stock-logistics-barcode/pull/178#issuecomment-511463341 ?
I still have this after the sequence : 
```
git format-patch --keep-subject --stdout origin/10.0..origin/11.0 --  product_multi_ean | git am -3 --keep
Application de  [ADD] moved modules
Utilisation de l'information de l'index pour reconstruire un arbre de base...
Retour à un patch de la base et fusion à 3 points...
CONFLIT (ajout/ajout) : Conflit de fusion dans product_multi_ean/product_view.xml
Fusion automatique de product_multi_ean/product_view.xml
CONFLIT (ajout/ajout) : Conflit de fusion dans product_multi_ean/product_ean.py
Fusion automatique de product_multi_ean/product_ean.py
error: Échec d'intégration des modifications.
le patch a échoué à 0001 [ADD] moved modules
astuce: Utilisez 'git am --show-current-patch' pour visualiser le patch en échec
Quand vous avez résolu ce problème, lancez "git am --continue".
Si vous préférez plutôt sauter ce patch, lancez "git am --skip".
Pour restaurer la branche originale et arrêter de patcher, lancez "git am --abort".
```
Its like the structure of the  v11.0 was not kept in the am process.
What am I doing wrong

**Comment by pedrobaeza** [comment]
There was a merge commit in the middle of the commit history, and you have to resolve that conflicts. That's happened because of sins of the past (remember the prestashop connector).

**Comment by flotho** [comment]
@pedrobaeza ,

thanks for your patience

so first I solve the conflicts and then the history will produce all the latets structure of the v11 ?

**Pull request closed without merging**
