### PR TITLE
[14.0] mig stock scanner

### PR DESCRIPTION
**Pull request by sla-subteno-it**

### CODE REVIEW

**Review by dsolanki-initos — CHANGES_REQUESTED** [review]
Code review and functional test LGTM Can you make checks happy?

**Comment by dsolanki-initos** [comment]
Can you make checks happy?

**Comment by rousseldenis** [comment]
@sla-subteno-it

**Comment by dsolanki-initos** [comment]
Can you make checks happy?

**Comment by dsolanki-initos** [comment]
Can you make checks happy?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it it would be nice if you make all the checks happy?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it  could you check this pull and resolve the travis issue.

**Comment by dsolanki-initos** [comment]
@sla-subteno-it  It would be nice if can fix the failed checks

**Comment by dsolanki-initos** [comment]
@sla-subteno-it Can you please fix the failed checks?

**Comment by dsolanki-initos** [comment]
Hello @sla-subteno-it,
Can you please fix the failed checks?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it it would be nice to see all the failed checked to green.

**Comment by dsolanki-initos** [comment]
@sla-subteno-it it would be nice to see all the failed checked to green.

**Comment by dsolanki-initos** [comment]
@sla-subteno-it can you please check failed checks

**Comment by dsolanki-initos** [comment]
@sla-subteno-it Can we see all checks green?

**Comment by rousseldenis** [comment]
@sla-subteno-it Could you rebase too as we swtiched to github actions ?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it can we please check the failed chekcs?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it can we see travis green?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it can we see all checks green?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it can you please fix failed checks?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it Can you please fix the failed checks?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it can you please the failed checks?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it Can we see failed checks to green?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it can you please check failed checks?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it can you please check to fail checks?

**Comment by dsolanki-initos** [comment]
@sla-subteno-it can you please check failed checks?

**Pull request closed without merging**
