### PR TITLE
[15.0][MIG] stock_barcodes

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration
@ForgeFlow

To Do:
 - need to take care of inventory adjustment-related changes as stock.inventory model removed from v15

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@sergio-teruel inventory adjustment model has been removed in v15, which is impacting this module. Any suggestion or idea on the path to follow?

**Comment by sergio-teruel** [comment]
I do not research the v15 inventory so at the moment I can't suggest anything... Sorry :cry:

**Comment by rousseldenis** [comment]
@JasminSForgeFlow @LoisRForgeFlow @sergio-teruel @legalsylvain 

As pointed https://github.com/OCA/stock-logistics-warehouse/issues/1328

I would suggest to introduce a new repository called stock-inventory if needed (but I think so)

**Comment by LoisRForgeFlow** [comment]
Closed in favor of https://github.com/OCA/stock-logistics-barcode/pull/428 that include the latest refactor done in v13 and v14.

**Pull request closed without merging**
