### PR TITLE
[8.0] update travis config

### PR DESCRIPTION
**Pull request by yvaucher**
superseeds #14

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by tafaRU** [comment]
@yvaucher not need https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L16-L18 ?

**Comment by yvaucher** [comment]
@tafaRU All are dependencies of odoo 8.0 thus I can add them in the list. I guess we added them for performances over pip even if it is in cache.

I'm curious if next build makes it faster.

LINT_CHECK="1"
 39 sec

TRANSIFEX="1"
3 min 8 sec

TESTS="1" ODOO_REPO="OCA/OCB"
2 min 37 sec

TESTS="1" ODOO_REPO="odoo/odoo"
2 min 21 sec

**Comment by gurneyalex** [comment]
@yvaucher can you rebase please?

**Comment by gurneyalex** [comment]
after rebasing, nothing left to merge --> closing

**Comment by yvaucher** [comment]
@gurneyalex thanks

**Pull request closed without merging**
