### PR TITLE
[14.0] [mig] stock_barcodes_automatic_entry

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by dsolanki-initos** [comment]
@AdriaGForgeFlow  Can you please review this PR?

**Comment by AdriaGForgeFlow** [comment]
> @AdriaGForgeFlow Can you please review this PR?

I will try to get some time next week to review the PR :+1:

**Comment by dsolanki-initos** [comment]
@AdriaGForgeFlow It would be great if you can get some time to review the PR this week.

**Comment by dsolanki-initos** [comment]
@JoanSForgeFlow It would be great if you can review the PR.

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews here.

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1: 

I'm not able to do a functional review

**Comment by dsolanki-initos** [comment]
It would be nice if we could merge the PR.

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews and merge the PR.

**Review by fshah-initos — APPROVED** [review]
LGTM. No major change

**Comment by dsolanki-initos** [comment]
It would be great if the maintainers can merge the PR.

**Comment by dsolanki-initos** [comment]
It would be great if the maintainers can merge the PR.

**Comment by dsolanki-initos** [comment]
It would be great if the maintainers can merge the PR.

**Comment by dsolanki-initos** [comment]
It would be great if the maintainers can merge the PR.

**Comment by dsolanki-initos** [comment]
It would be great if the maintainers can merge the PR.

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by hkapatel-initos** [comment]
Hi, @LoisRForgeFlow  it would be nice if could you merge this?

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by LoisRForgeFlow** [comment]
Hi, you are really persevering :wink: We try do our best to attend/review the pull requests in our spare time, thanks for being patient.

/ocabot merge nobump

**Pull request merged**
