### PR TITLE
[8.0][ADD][stock_disable_barcode_interface] Disable and enable the barcode interface

### PR DESCRIPTION
**Pull request by tarteo**
This module makes it possible to disable and enable (configurable) the barcode interface system wide. Maybe it's a good idea to also add this configuration on operation (stock.picking.type) but I need someone to confirm this.

I'm not sure if this is the right repository.

### CODE REVIEW

**Comment by lasley** [comment]
@tarteo - Thanks for the submission! This is the best repo I can think of for it as well.

👍  but would you mind squashing your commits into one please?

**Comment by lasley** [comment]
Also regarding adding it on the picking type, you're meaning instead of a global config to allow a configuration for whether the interface is activated/deactivated at the picking type instead? 

I'm typically all for granularity, but I can't personally think of a use case. As I'm thinking about it, making this a user permission may be the best bet if we want to get granular.

**Comment by tarteo** [comment]
@lasley Thanks for your comment. I've squashed the commits together.

**Comment by lasley** [comment]
Thanks @tarteo - 👍

**Review by susport — COMMENTED** [review]
I am trying the runbot but the admin user does not see the check Enable barcode interface.I imagine it's because of the permission of group group_enable_barcode. Thank

**Comment by tarteo** [comment]
@susport It's the last checkbox of Settings -> Configuration -> Warehouse
checkbox

**Review by lasley — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
