### PR TITLE
[13.0][MIG] product_multi_ean

### PR DESCRIPTION
**Pull request by jimhoefnagels**

### CODE REVIEW

**Review by qgroulard — APPROVED** [review]
Code review :+1:

**Comment by tonygalmiche** [comment]
I have this error modifying the Barcode field : 

image

**Comment by jjscarafia** [comment]
I've made new PR for this with some improvements https://github.com/OCA/stock-logistics-barcode/pull/341

**Comment by rousseldenis** [comment]
closing as this has been done there #345

**Pull request closed without merging**
