### PR TITLE
[8.0] stock_scanner_web

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Backport of https://github.com/OCA/stock-logistics-barcode/pull/55 to 8.0

### CODE REVIEW

**Comment by lasley** [comment]
@lreficent - looks like CI is failing 😦

**Comment by LoisRForgeFlow** [comment]
I fixed some syntax error but this will still fail since <code>stock_scanner</code> is not backported to v8. @lasley 

edit: see comment below.

**Comment by LoisRForgeFlow** [comment]
mmm I've just realized that <code>stock_scanner</code> is in <a href="https://github.com/OCA/stock-logistics-workflow/tree/8.0">stock-logistics-workflow v8</a>. How can I make runbot to find the dependency in a different repository? @lasley

**Comment by lasley** [comment]
@lreficent Easy enough! Just create an `oca_dependencies.txt` file in the root of the repo with the following:
```
stock-logistics-workflow
```

Then `stock-logistics-workflow` will be downloaded and added to the addons dirs for use before testing

**Comment by LoisRForgeFlow** [comment]
Runbot is green now!  :ok_hand: Thank you @lasley!

**Comment by lasley** [comment]
@lreficent - Sweet looks like it is! We should probably only review one of the PRs at a time in order to minimize duplication of efforts, did you want to work in the v9 or the v8? Are either ready for review?

**Comment by LoisRForgeFlow** [comment]
@lasley I think it is better to stick to v9, @angelmoya is reviewing it in v9 and I think we'll be adding some changes there.

**Comment by legalsylvain** [comment]
closing as no news since 2 years.

**Pull request closed without merging**
