### PR TITLE
[15.0][IMP] stock_barcodes_gs1: Refactoring. Use Odoo core module to decode GS1 barcodes

### PR DESCRIPTION
**Pull request by sergio-teruel**
Better process of AI's

cc @Tecnativa TT45427

ping @carlosdauden @CarlosRoca13 @dalonsod @etobella 

Depends on:
- [x] https://github.com/OCA/stock-logistics-barcode/pull/495

### CODE REVIEW

**Comment by pedrobaeza** [comment]
On organization branches, only manual rebase and push can be done. This is due to GitHub forbidding it.

**Comment by sergio-teruel** [comment]
Rebase done... 
I have to fix tests without stock_barcodes_gs1_expiry module installed

**Review by carlosdauden — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge major

**Pull request merged**
