### PR TITLE
[14.0][FIX] stock_barcodes: restore read_inventory to old version

### LINKED ISSUE #565: [14.0] stock_barcodes: regression on inventory
The PR https://github.com/OCA/stock-logistics-barcode/pull/560 by @dalonsod  has introduced a regression: it uses the fields "user_id", "inventory_quantity_set" and "inventory_date" and  on stock.quant, which exists on odoo v15 but NOT on odoo v14 !

There is the code which uses the non-existing user_id + inventory_quantity_set + fields inventory_date on stock.quant: https://github.com/OCA/stock-logistics-barcode/blob/14.0/stock_barcodes/wizard/stock_barcodes_read_inventory.py#L28

### PR DESCRIPTION
**Pull request by dalonsod**
Fixes #565 introduced by #560

### CODE REVIEW

**Comment by dalonsod** [comment]
Added post-migration script due to `noupdate_changes.xml` required file.

**Comment by francesco-ooops** [comment]
@dalonsod can you add some tests to PR or do you prefer we pick it up and add them? thanks!

**Comment by dalonsod** [comment]
Thanks @francesco-ooops I'm currently too busy, so your help is welcome! Feel free to supersede it

**Comment by dalonsod** [comment]
Superseded by #582 , closing this

**Pull request closed without merging**
