### PR TITLE
[10.0][FIX] pip install external dependencies broken #101

### LINKED ISSUE #100: pip install is broken for barcodes_generator_abstract
when running the command
`pip install odoo10_addon_barcodes_generator_abstract`

The command fails with the following stack trace:
```
Downloading/unpacking odoo10-addon-barcodes-generator-product
  Downloading odoo10_addon_barcodes_generator_product-10.0.1.0.0-py2-none-any.whl (67kB): 67kB downloaded
Downloading/unpacking odoo10-addon-barcodes-generator-abstract (from odoo10-addon-barcodes-generator-product)
  Downloading odoo10_addon_barcodes_generator_abstract-10.0.1.0.0-py2-none-any.whl (121kB): 121kB downloaded
Requirement already satisfied (use --upgrade to upgrade): odoo>=10.0,<10.1dev in /usr/lib/python2.7/dist-packages (from odoo10-addon-barcodes-generator-product)
Downloading/unpacking barcode (from odoo10-addon-barcodes-generator-abstract->odoo10-addon-barcodes-generator-product)
  Downloading barcode-0.6.0.tar.gz
  Running setup.py (path:/tmp/pip-build-Y4M0Yo/barcode/setup.py) egg_info for package barcode
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-Y4M0Yo/barcode/setup.py", line 16, in <module>
        import barcode as distmeta
      File "barcode/__init__.py", line 10, in <module>
        from .barcode import filter_distance, all_barcodes, filter_stretches
      File "barcode/barcode.py", line 1, in <module>
        import Levenshtein
    ImportError: No module named Levenshtein
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-Y4M0Yo/barcode/setup.py", line 16, in <module>

    import barcode as distmeta

  File "barcode/__init__.py", line 10, in <module>

    from .barcode import filter_distance, all_barcodes, filter_stretches

  File "barcode/barcode.py", line 1, in <module>

    import Levenshtein

ImportError: No module named Levenshtein
```

Wouldn't adding this to setup.py fix the issue? EDIT: I see now that this not how Odoo packaging is done
```python
from setuptools import setup

setup(
install_requires=[
          'viivakoodi',
      ],
)
```

EDIT:
I see now the setuptools-odoo is generating the wheels by parsing the odoo module manifest files. I put in what I'm guessing will fix this in #101. I'll try and confirm that this fix works shortly.

### PR DESCRIPTION
**Pull request by hparfr**
Fixes #100 #101 

ping @sbidoul can you please confirm it's the right way to do ?

### CODE REVIEW

**Comment by sbidoul** [comment]
Assuming `viivakoodi` is the distribution that provides the `barcode` package, yes, it looks good.

**Review by legalsylvain — APPROVED** [review]
:+1: thanks !

**Review by lmignon — APPROVED** [review]

**Comment by yucer** [comment]
Is there another project [python-barcode](https://github.com/WhyNotHugo/python-barcode) that seems to be a fork from [viivakoodi](https://github.com/kxepal/viivakoodi). It has additional releases and cleaner packaging.

Also it has less TODOs. One of them *Improve Python 3 support* seems to be done. Do you thing it can be used instead of **viivakoodi** ?

**Comment by legalsylvain** [comment]
Hi @yucer 
thanks for your question. 
 It's not the right place to talk about that point.

I opened a new issue for that purpose. Feel free to contribute.
https://github.com/OCA/stock-logistics-barcode/issues/193

kind regards.

**Pull request merged**
