### PR TITLE
[17.0][MIG] barcodes_generator_abstract: Migration to 17.0

### PR DESCRIPTION
**Pull request by niboo-jva**

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Diff review

**Comment by rousseldenis** [comment]
@jvandri Thanks for this. Could you add odoo-test-helper to test-requirements.txt ?

**Comment by desdelinux** [comment]
Test is red @jvandri

**Comment by pedrobaeza** [comment]
Superseded by #615 as lack of answer here.

**Pull request closed without merging**
