### PR TITLE
10.0 mig stock inventory barcode

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by gurneyalex** [comment]
superseeds #123 : I squashed the translation commits

**Review by alexis-via — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by alexis-via — APPROVED** [review]

**Comment by gurneyalex** [comment]
I rebased to get a fresh build.

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
