### PR TITLE
[12.0][IMP] stock_barcodes_gs1: Allow the use of double GS1-128 barcodes

### PR DESCRIPTION
**Pull request by etobella**
This way we can use barcodes like the following:

imagen

@LoisRForgeFlow

### CODE REVIEW

**Comment by etobella** [comment]
The other option would be to improve the `reset_qty` function, but It has some implications :thinking:

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, LGTM :+1:

**Review by jarroyomorales — APPROVED** [review]
LGTM :+1:

**Comment by etobella** [comment]
@sergio-teruel Can I kindly ask for your review? :pray:

**Review by sergio-teruel — APPROVED** [review]
@etobella Sorry... Ready!!

**Comment by sergio-teruel** [comment]
@etobella Can you port to v13 0... ??

**Pull request merged**
