### PR TITLE
[9.0] Add stock_scanner_location_info module

### PR DESCRIPTION
**Pull request by Garamotte**
This PR is based on https://github.com/OCA/stock-logistics-barcode/pull/40

It adds a scenario module : Location information

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi,

Great work ! Good to split one module per scenario. Just a little remark:

I saw you have a common readme for all scenarios modules. It would be nice to have instead a explanation of the scenario it-self.

Regards,

Joël

**Comment by jgrandguillaume** [comment]
:+1:  After discussion :)

**Comment by Garamotte** [comment]
@jgrandguillaume : The readme was missing in the scenario modules.
I added a readme in each one, displaying a screenshot of Odoo's diagram view and a short description.

**Comment by pedrobaeza** [comment]
Can you squash a bit the commit list?

**Comment by Garamotte** [comment]
No, I can't. The only commit added by this PR is the last.
All other commits are from #40, which adds the `stock_scanner` module.

**Comment by Garamotte** [comment]
@pedrobaeza : Now that the stock_scanner module has been merged, Github only displays one commit in the diff :)

**Comment by pedrobaeza** [comment]
Then please make the squash in the other one and rebase after merging the other one here :wink:

**Comment by Garamotte** [comment]
@pedrobaeza : The rebase was already done on top of the other PR, which has been merged.

I emptied the **init**.py file, which contained nothing else than a big license comment and a vim line.

**Review by pedrobaeza — APPROVED** [review]

**Review by lasley — APPROVED** [review]
Thanks @sylvain-garancher

**Pull request merged**
