### PR TITLE
[MIG][11.0] Migrate barcodes_generator_abstract

### PR DESCRIPTION
**Pull request by phatnguyenuit**
[MIG][11.0] Migrate barcodes_generator_abstract

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You should respect commit history. Please follow migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by phatnguyenuit** [comment]
Should I close this pull request and open the new one?

**Comment by pedrobaeza** [comment]
No, simply overwrite your branch with the correct commits. You can remove your local git branch, then redo the work with a new branch with the same name, and finally push with `-f` to your remote for overwriting the branch, and this PR will be automatically refreshed.

**Review by gurneyalex — APPROVED** [review]

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @phatnguyenuit. 
Thanks for porting this work. The PR LGTM to me. However, I dont understand why you set Komit as author in all files. The changes introduced in your commit are all trivials, and it doesn't seems me fair.

https://github.com/OCA/stock-logistics-barcode/pull/122/commits/cfbf81548c0c76dc6dbdea1f40bf33272c4d6649

what do you think ?

kind regards.

**Comment by phatnguyenuit** [comment]
Hi @legalsylvain!
I updated changes in the new commit. Could you have a look?

**Comment by legalsylvain** [comment]
Hi.
 
- It left some "Komit" reference in some files.
- could you cherry pick 36b6313a43a83596676e4f9cd357239c5be270e2 present in https://github.com/OCA/stock-logistics-barcode/pull/136 ?

kind regards.

**Comment by misern2** [comment]
Hi @phatnguyenuit.

LGTM. Could you please apply the changes suggested by @legalsylvain  ?


Thanks!

**Comment by pedrobaeza** [comment]
Superseeded by #138

**Pull request closed without merging**
