### PR TITLE
[14.0] [mig] stock_barcodes_move_location

### PR DESCRIPTION
**Pull request by fshah-initos**
Depends on:
1) stock_barcodes #330 
2) stock_move_location (https://github.com/OCA/stock-logistics-warehouse/tree/14.0/stock_move_location)
3) stock_barcodes_automatic_entry #331 

During the migration of the module I found that there is an error from the depended module "stock_move_location" which is as below:
Move-Between-Locations-Mitchell-Admin-Odoo

### CODE REVIEW

**Comment by fshah-initos** [comment]
@joao-p-marques It would be great if could have a look at the issue as you have mikgrated the module stock_move_location.

**Comment by joao-p-marques** [comment]
@fshah-initos can you provide more info on how to reproduce this?

**Comment by fshah-initos** [comment]
> @fshah-initos can you provide more info on how to reproduce this?

Okay I'll will provide you the steps to reproduce above error.

**Comment by fshah-initos** [comment]
Hi @joao-p-marques 
Please find the video link for steps to reproduce the scenrios.

https://www.awesomescreenshot.com/video/3697541?key=73296e248a90bd28ede16c34608c6d43

**Comment by fshah-initos** [comment]
Hi @joao-p-marques did you get chnace to check above scnerio?

**Comment by joao-p-marques** [comment]
Sorry, but I can't reproduce this... Could it be an error in something in your environment or with your code changes?

**Comment by fshah-initos** [comment]
> Sorry, but I can't reproduce this... Could it be an error in something in your environment or with your code changes?

NO error is not in my code I have checked it

**Comment by fshah-initos** [comment]
I've double checked. Now I am getting singletone error.
Please find the attachment:
Move-Between-Locations-Odoo

**Comment by fshah-initos** [comment]
It would be great if someone could help me with this Issue

**Comment by hkapatel-initos** [comment]
It would be great if someone help to resolve this Issue

**Comment by hkapatel-initos** [comment]
It would be great if someone help to resolve this Issue

**Comment by joao-p-marques** [comment]
@fshah-initos @hkapatel-initos I am sorry, but I still can't reproduce the error you mention... I just tested in the OCA runbot for that module and it works as expected. 

Please, if this is a true bug, provide all the proper information (the environment of modules you have installed, all the steps performed before, the products you have created, etc) and possibly open another issue to track it, instead of just in this PR, as that will make it easier for the community to be aware of the problem and respond.

I looks to me that this might be an incompatibility or integration error with some other module you have installed, or some inconsistency in the data in your DB.

**Comment by hkapatel-initos** [comment]
> @fshah-initos @hkapatel-initos I am sorry, but I still can't reproduce the error you mention... I just tested in the OCA runbot for that module and it works as expected.
> 
> Please, if this is a true bug, provide all the proper information (the environment of modules you have installed, all the steps performed before, the products you have created, etc) and possibly open another issue to track it, instead of just in this PR, as that will make it easier for the community to be aware of the problem and respond.
> 
> I looks to me that this might be an incompatibility or integration error with some other module you have installed, or some inconsistency in the data in your DB.

 I have checked it in the new DB, the error is not in my code it is from the dependent module "stock_move_location".

**Comment by hkapatel-initos** [comment]
Hello, it would be nice if someone can help me to resolve this issue.
During the migration of the module I found that there is an error from the dependent module "stock_move_location" which is as below:
https://www.awesomescreenshot.com/video/5176198?key=30e4661941822f45aef03b48c9b248d3
Here is the detailed log:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/workspace/community/odoo_14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/workspace/community/odoo_14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/workspace/community/odoo_14.0/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/workspace/community/odoo_14.0/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/workspace/community/odoo_14.0/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/workspace/community/odoo_14.0/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/initos/documentt/stock_move_location/wizard/stock_move_location.py", line 220, in action_move_location
    self._create_moves(picking)
  File "/home/odoo/initos/documentt/stock_move_location/wizard/stock_move_location.py", line 155, in _create_moves
    move = self._create_move(picking, lines)
  File "/home/odoo/initos/documentt/stock_move_location/wizard/stock_move_location.py", line 182, in _create_move
    line.create_move_lines(picking, move)
  File "/home/odoo/initos/documentt/stock_move_location/wizard/stock_move_location_line.py", line 82, in create_move_lines
    values = line._get_move_line_values(picking, move)
  File "/home/odoo/initos/documentt/stock_move_location/wizard/stock_move_location_line.py", line 91, in _get_move_line_values
    self.move_location_wizard_id.apply_putaway_strategy
  File "/home/odoo/workspace/community/odoo_14.0/odoo/fields.py", line 963, in __get__
    record.ensure_one()
  File "/home/odoo/workspace/community/odoo_14.0/odoo/models.py", line 4993, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: wiz.stock.move.location(1, 5, 9, 10)

**Comment by hkapatel-initos** [comment]
> Hello, it would be nice if someone can help me to resolve this issue.
> During the migration of the module I found that there is an error from the dependent module "stock_move_location" which is as below:
> 
> https://www.awesomescreenshot.com/video/5176198?key=30e4661941822f45aef03b48c9b248d3
> Here is the detailed log:
> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
> File "/home/odoo/workspace/community/odoo_14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
> result = request.dispatch()
> File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 684, in dispatch
> result = self._call_function(**self.params)
> File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 360, in _call_function
> return checked_call(self.db, *args, **kwargs)
> File "/home/odoo/workspace/community/odoo_14.0/odoo/service/model.py", line 94, in wrapper
> return f(dbname, *args, **kwargs)
> File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 348, in checked_call
> result = self.endpoint(*a, **kw)
> File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 913, in **call**
> return self.method(*args, **kw)
> File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 532, in response_wrap
> response = f(*args, **kw)
> File "/home/odoo/workspace/community/odoo_14.0/addons/web/controllers/main.py", line 1393, in call_button
> action = self._call_kw(model, method, args, kwargs)
> File "/home/odoo/workspace/community/odoo_14.0/addons/web/controllers/main.py", line 1381, in _call_kw
> return call_kw(request.env[model], method, args, kwargs)
> File "/home/odoo/workspace/community/odoo_14.0/odoo/api.py", line 396, in call_kw
> result = _call_kw_multi(method, model, args, kwargs)
> File "/home/odoo/workspace/community/odoo_14.0/odoo/api.py", line 383, in _call_kw_multi
> result = method(recs, *args, **kwargs)
> File "/home/odoo/initos/documentt/stock_move_location/wizard/stock_move_location.py", line 220, in action_move_location
> self._create_moves(picking)
> File "/home/odoo/initos/documentt/stock_move_location/wizard/stock_move_location.py", line 155, in _create_moves
> move = self._create_move(picking, lines)
> File "/home/odoo/initos/documentt/stock_move_location/wizard/stock_move_location.py", line 182, in _create_move
> line.create_move_lines(picking, move)
> File "/home/odoo/initos/documentt/stock_move_location/wizard/stock_move_location_line.py", line 82, in create_move_lines
> values = line._get_move_line_values(picking, move)
> File "/home/odoo/initos/documentt/stock_move_location/wizard/stock_move_location_line.py", line 91, in _get_move_line_values
> self.move_location_wizard_id.apply_putaway_strategy
> File "/home/odoo/workspace/community/odoo_14.0/odoo/fields.py", line 963, in **get**
> record.ensure_one()
> File "/home/odoo/workspace/community/odoo_14.0/odoo/models.py", line 4993, in ensure_one
> raise ValueError("Expected singleton: %s" % self)
> Exception
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 640, in _handle_exception
> return super(JsonRequest, self)._handle_exception(exception)
> File "/home/odoo/workspace/community/odoo_14.0/odoo/http.py", line 316, in _handle_exception
> raise exception.with_traceback(None) from new_cause
> ValueError: Expected singleton: wiz.stock.move.location(1, 5, 9, 10)

**Comment by hkapatel-initos** [comment]
Hi, @AaronHForgeFlow it would be nice if could you suggest me better way to fix the issue.

**Comment by hkapatel-initos** [comment]
it would be nice if someone suggest me better way to fix the issue.

**Comment by hkapatel-initos** [comment]
it would be nice if someone suggest me better way to fix the issue.

**Comment by dsolanki-initos** [comment]
It would be great if someone help to resolve this Issue

**Comment by dsolanki-initos** [comment]
It would be great if someone help to resolve this Issue

**Comment by dsolanki-initos** [comment]
It would be great if someone help to resolve this Issue

**Comment by AaronHForgeFlow** [comment]
Hi all, it seems the field move_location_wizard_id is empty at the time you create the wizard "Wizard move location line". That is something that is not happening in the normal use of the module stock_move_location, so the issue is actually in this migration.

**Comment by AaronHForgeFlow** [comment]
Also, The field move_location_wizard_id is many2many for technical reasons but actually there is going to be just per wizard.

**Comment by AaronHForgeFlow** [comment]
Can you at least specify the steps in Odoo to reproduce the error?

**Comment by dsolanki-initos** [comment]
> Can you at least specify the steps in Odoo to reproduce the error?
 I would like to share this video of an error from the dependent module "stock_move_location":
currently, I'm facing this issue https://www.awesomescreenshot.com/video/5176198?key=30e4661941822f45aef03b48c9b248d3

**Comment by dsolanki-initos** [comment]
@AaronHForgeFlow will you please check this issue?

**Comment by AaronHForgeFlow** [comment]
Looking at the video It seems there are several wizards created instead of one. I will try to have a look but I don't have much time for it.

**Comment by dsolanki-initos** [comment]
> Looking at the video It seems there are several wizards created instead of one. I will try to have a look but I don't have much time for it.

This issue error generates from the dependent module. so it would be nice if you fix this issue.

**Pull request closed without merging**
