### PR TITLE
[14.0][ADD] barcodes_generator_product_multi_barcode

### PR DESCRIPTION
**Pull request by dessanhemrayev**
superseding PR #448 
Updated test

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok! 

@legalsylvain what do you think?

**Comment by francesco-ooops** [comment]
@legalsylvain gentle reminder :)

**Review by Aldeigja — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@OCA/logistics-maintainers shall we? :)

**Comment by francesco-ooops** [comment]
@OCA/logistics-maintainers could you please take a look? thanks!

**Comment by francesco-ooops** [comment]
@simahawk what do you say? :)

**Comment by francesco-ooops** [comment]
@OCA/logistics-maintainers gentle reminder

**Comment by jbaudoux** [comment]
As it is a new module, could you rewrite commit message to `[ADD] barcodes_generator_product_multi_barcode`

**Comment by francesco-ooops** [comment]
@jbaudoux good for you? :)

**Pull request merged**
