### PR TITLE
[10.0][FIX] barcodes_generator_abstract: Caching issue

### LINKED ISSUE #93: OperationalError: Unable to use a closed cursor.
Hello, I´m in Odoo v10.0 CE, i want to autogenerate the barcode EAN-13 in the new products.
I Install **barcodes_generator_abstract** and **barcodes_generator_product**.
I generate a barcode nomenclature and barcode pattern 23...........
The first generation of barcode works well, but if i want to create a new products, this is the error:
If i update the addon barcodes_generator_product works well one more time but in the second time fail again.

```
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 882, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 874, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons/barcodes_generator_product/models/product_template.py", line 45, in create
    template = super(ProductTemplate, self).create(vals)
  File "/odoo/odoo-server/addons/product/models/product_template.py", line 267, in create
    template.create_variant_ids()
  File "/odoo/odoo-server/addons/product/models/product_template.py", line 400, in create_variant_ids
    'attribute_value_ids': [(6, 0, variant_ids.ids)]
  File "/odoo/odoo-server/addons/product/models/product.py", line 315, in create
    product = super(ProductProduct, self.with_context(create_product_product=True)).create(vals)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/odoo/custom/addons/barcodes_generator_abstract/models/barcode_generate_mixin.py", line 40, in create
    if barcode_rule.exists():
  File "/odoo/odoo-server/odoo/models.py", line 4406, in exists
    self._cr.execute(query, [tuple(ids)])
  File "/odoo/odoo-server/odoo/sql_db.py", line 140, in wrapper
    **raise psycopg2.OperationalError(msg)
OperationalError: Unable to use a closed cursor.**
```

The explication of the error:
**exception psycopg2.OperationalError**
Exception raised for errors that are related to the database’s operation and not necessarily under the control of the programmer, e.g. an unexpected disconnect occurs, the data source name is not found, a transaction could not be processed, a memory allocation error occurred during processing, etc. It is a subclass of DatabaseError.

### PR DESCRIPTION
**Pull request by lasley**
* Make cache method return ids & move the recordset method out of cache to fix #93

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't better to call to `.invalidate()` before reading data?

**Comment by lasley** [comment]
@pedrobaeza - What is the `invalidate()`? I know of `_clear_cache`, which is called in the [`create`](https://github.com/OCA/stock-logistics-barcode/blob/10.0/barcodes_generator_abstract/models/barcode_rule.py#L90) and [`write`](https://github.com/OCA/stock-logistics-barcode/blob/10.0/barcodes_generator_abstract/models/barcode_rule.py#L95), which should invalidate when we need it to. Am I missing a nuance?

**Comment by pedrobaeza** [comment]
Sorry, I mean `invalidate_cache`: 

https://github.com/odoo/odoo/blob/cf8985e37d48ead868c83a4589b2f755f57de379/odoo/models.py#L5252

**Comment by lasley** [comment]
Oh crap I'm using the wrong methods. Thanks Pedro!

**Comment by pedrobaeza** [comment]
@lasley actually you are right about not storing in ORM cache a browse_record. See https://github.com/odoo/odoo/pull/8795 for a similar case.

**Comment by lasley** [comment]
Good call, thanks for the confirmation and Odoo core example case @pedrobaeza. I feel like this is worthy of documentation, so I created odoo/odoo#19113.

I think you're still right about the use of `invalidate_cache` though - I can't even find `_clear_cache` in the Odoo 10 codebase. I find it strange where the hell I would have gotten this method - this wasn't even migrated code 😑 

I'll make the fix today 

_Edit: Ughhh I needed coffee. I'm using `clear_caches` - will still double check the necessity, but will also leave the above so you can laugh at me if you'd like_

**Comment by piqoni** [comment]
Thanks for this fix, any idea when will this be merged? I also got the same cursor error and this fixed it. :)

**Review by legalsylvain — COMMENTED** [review]
Hi @lasley. Sorry but I don't understand cache system very well, so I'm not the person the most adapted to review this change. (I never used ```@tools.ormcache```)

thanks for investigating this bug.

I'm sure that @StefanRijnhart, or other core experts  will have a more interesting point of view than mine.

regards.

**Comment by lasley** [comment]
@piqoni - We need two reviews to merge, one from someone with write access. If you have reviewed and confirmed this works, please add it officially in Files Changed => Review Changes => Approve

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Comment by pedrobaeza** [comment]
Please change module version number

**Comment by lasley** [comment]
It's interesting how many people I call out on version numbers, but how many times I screw up the exact same thing myself.

Done!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
