### PR TITLE
[MIG] Migrate stock_scanner to v10.0

### PR DESCRIPTION
**Pull request by Garamotte**
The module didn't need any modification to technically work on v10.

I just applied new naming :
- In XML files : openerp/data > odoo
- In python files : import openerp > import odoo
- Renamed the manifest from `__openerp__.py` to `__manifest__.py`

### CODE REVIEW

**Comment by Garamotte** [comment]
Runbot green, but it tested on the Odoo's 7.0 branch, ans no other module than base was installed ?! (according to the test instance's log)

@gurneyalex : The runbot says "Server branch cannot be determined exactly. Please use naming convention '9.0-my-branch' to build with '9.0' server branch."
Is it possible that it searches for a single digit (9.0) instead of two (10.0) ?

**Comment by pedrobaeza** [comment]
Runbot should be now working. Please restart build.

**Comment by Garamotte** [comment]
@pedrobaeza : All 20 "testing" builds on runbot seem to be blocked.
I think you should reset their state to "pending" tu unblock the runbot.

**Comment by pedrobaeza** [comment]
I'm afraid we have to wait. Maybe it's stuck, and we have to restart server... Let's see tomorrow. Now there are 115 pending builds.

**Review by alexis-via — APPROVED** [review]
Thanks for this port to v10 !

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
