### PR TITLE
[12.0][MIG] base_gs1_barcode

### PR DESCRIPTION
**Pull request by mediaengagers**

### CODE REVIEW

**Comment by sergio-teruel** [comment]
@mediaengagers I think that this migration PR should be based on the PR https://github.com/OCA/stock-logistics-barcode/pull/192 (Migration to V11.0).
I see that you transform test.yaml to python file.. I will do a cherry pick for V11.0, ok?

**Comment by mediaengagers** [comment]
> @mediaengagers I think that this migration PR should be based on the PR #192 (Migration to V11.0).
> I see that you transform test.yaml to python file.. I will do a cherry pick for V11.0, ok?

yes for sure

**Comment by pedrobaeza** [comment]
@mediaengagers now you can base your migration in 11.0 branch for getting all the changes we have done there.

**Comment by rousseldenis** [comment]
@mediaengagers

**Comment by LoisRForgeFlow** [comment]
@mediaengagers can you add https://github.com/OCA/stock-logistics-barcode/pull/230 here?

**Comment by LoisRForgeFlow** [comment]
@mediaengagers Are you going to continue this work?

**Comment by mediaengagers** [comment]
> @mediaengagers Are you going to continue this work?

yes but need few days.. overloaded in some projects

**Comment by LoisRForgeFlow** [comment]
Hi @mediaengagers 

Don't worry, we all have been there, thanks for the effort. Let us help here, we are going to supersede this migration here: https://github.com/OCA/stock-logistics-barcode/pull/235. Let's see if we speed think up a little bit :smiley:

**Pull request closed without merging**
