### PR TITLE
[14.0][MIG/IMP] stock_barcodes: refactor, add guided mode

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
This PR forward ports the following ones:

* https://github.com/OCA/stock-logistics-barcode/pull/348
* https://github.com/OCA/stock-logistics-barcode/pull/414
* https://github.com/OCA/stock-logistics-barcode/pull/415

@ForgeFlow

### CODE REVIEW

**Review by DavidJForgeFlow — APPROVED** [review]
Functional test :+1: . The code also LGTM

**Comment by pedrobaeza** [comment]
Please add #419

**Comment by pedrobaeza** [comment]
Please add #421

**Comment by pedrobaeza** [comment]
Another one to take into account: #422

**Comment by pedrobaeza** [comment]
And a new one that is complement: #423

**Comment by pedrobaeza** [comment]
And another one more: #424

**Comment by sergio-teruel** [comment]
I think that we can merge this PR.

ping @LoisRForgeFlow @pedrobaeza

**Comment by pedrobaeza** [comment]
OK, merging then, but please put in another PR the rest of the improvements:

/ocabot merge major

**Pull request merged**
