### PR TITLE
[15.0][IMP] stock_barcodes: Add pending move with difference between demand and reserved

### PR DESCRIPTION
**Pull request by carlosdauden**
@Tecnativa TT49738

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Is the false green (finished) appearance related to this? The commit history should be kept as is?

**Comment by carlosdauden** [comment]
@chienandalu can you review?

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sergio-teruel can you please squash according logical batches?

**Comment by carlosdauden** [comment]
@sergio-teruel review to merge

**Review by sergio-teruel — APPROVED** [review]

**Comment by carlosdauden** [comment]
Ready to merge

**Pull request merged**
