### PR TITLE
[MIG][14.0]  stock_barcodes_gs1_expiry

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Standard migration of the module, to version 14.0

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by mariadforgeflow — APPROVED** [review]
LGTM! Functional test and code review.

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
