### PR TITLE
[16.0][fix] barcodes_generator_*(package/product) : record is undefined

### LINKED ISSUE #591: [15.0][16.0] Bug report - Impossible to Open barcode Rule from product
## Module
barcode_generator_product

## Description
We just can't open Barcode Rule in [15.0] and [16.0] versions
I opened à runboat on 16.0

image

## To Reproduce
Just open a product and click on the arrow to open barcode rule

1. Go to products
2. Select one
3. Open barcode rule by clicking on the arrow

**Expected behavior**
Should open the barcode rule window

### PR DESCRIPTION
**Pull request by legalsylvain**
Fix :  #591

### CODE REVIEW

**Comment by legalsylvain** [comment]
CC : @OCA/logistics-maintainers

**Comment by legalsylvain** [comment]
@rousseldenis, could you take a look on this one. could be great to be included in V17 migration PR. Thanks

**Review by kikopeiro — APPROVED** [review]
:+1: LGTM

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
