### PR TITLE
[13.0][ADD] stock_barcodes_picking_batch: New module

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Comment by joao-p-marques** [comment]
This PR also needs https://github.com/OCA/stock-logistics-barcode/pull/348 to be merged first

**Comment by elvise** [comment]
@sergio-teruel can you rebase ?

**Comment by sergio-teruel** [comment]
@elvise Done!

**Comment by elvise** [comment]
> @elvise Done!

@sergio-teruel  Great! Let me check runboat :)

**Comment by elvise** [comment]
@sergio-teruel can you check Runboat ?

**Comment by sergio-teruel** [comment]
@elvise Fixed in product_gtin module...

**Comment by pedrobaeza** [comment]
@sergio-teruel please squash commits and put this as non-wip.

**Pull request merged**
