### PR TITLE
[11.0][IMP] stock_scanner: Ensure that transition names are unique within same scenario

### PR DESCRIPTION
**Pull request by ghost**
### Summary
When the scenario is exported, transition XMLID-s are being constructed using their `name` and `scenario_id.name` fields, so in case we're having multiple transitions w/ same name within the same scenario, only one of those is going to survive the export.

### CODE REVIEW

**Comment by ctr-subteno-it** [comment]
Hi - If you look at PR #132, I manage this already. I've prepared a V11 version that allows multiple transitions and steps with the same name, but I haven't yet tested it. It's based on the v10 version so it works the same way - do you want me to do a PR despite not being able to test ?

**Comment by ghost** [comment]
@ctribbeck yeah, just noticed that there is a PR solving this issue already :smile:
sure, go ahead, and I'll check that v11 runs properly

**Comment by ghost** [comment]
I should admit that your approach is better than mine :wink:

**Comment by ctr-subteno-it** [comment]
I've pushed it - thanks for testing! We have a v11 project but we're not yet ready to export the scenarios (and I'm not in that project). It's PR #133 (if you haven't seen it).

**Comment by pedrobaeza** [comment]
Closing as not needed with #134

**Pull request closed without merging**
