### PR TITLE
[10.0][ADD] barcodes_ean14: EAN 14 Barcode Nomenclature

### PR DESCRIPTION
**Pull request by lasley**
This adds GTIN (EAN14) barcode nomenclature to both Python and JavaScript for full compliance with the new barcodes interfaces.

This is a forward migration of #36 + a rename and removal of the abstract validator, which no longer seems useful.

### CODE REVIEW

**Comment by lasley** [comment]
Alright this is good to go, I renamed to `barcodes_ean14` and removed some abstract validator logic that now seems useless. The scope of this is now purely to add an EAN-14 nomenclature.

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by pedrobaeza — APPROVED** [review]

**Comment by lasley** [comment]
🎉  I love it when a build breaks & it is due to an old PR getting merged!

**Comment by pedrobaeza** [comment]
You are talking about your Docker, isn't it? Travis is green.

**Comment by lasley** [comment]
I am yeah, sorry should have been more specific. All is well!

**Pull request merged**
