### PR TITLE
[14.0] mig product multi ean

### PR DESCRIPTION
**Pull request by sebastienbeau**
Migrate from version 12.0

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Review by flotho — CHANGES_REQUESTED** [review]
Hi,
I've made some tests on runbot and have some comments.

- Won't it be a good idea to use barcode as a name instead ean13. The latest suppose that you're only using a specific norm.
- When you're starting from a template and configure variants, the UI of the variants does not propose the one2many options and also authorize to add a man barcode. Thus this data is not reported to the one2many. So please make it possible to either add directly multi barcode there.
- When working  on a template with no variant, if you input a barcode on the template it's not reported on the main variant.

Anyway thanks for the job already done

**Comment by sebastienbeau** [comment]
@flotho thanks for your feedback, i am going to fix it, and rename the model (Migration is a good time for doing it)

**Comment by bealdav** [comment]
Module could also be renamed in product_multi_barcode?

**Comment by kevinkhao** [comment]
renamed https://github.com/akretion/stock-logistics-barcode/pull/11

**Comment by jjscarafia** [comment]
hi @sebastienbeau @flotho 
We've been working on migration to v13 and I believe we have consider some of the improvements you have discuss here.
Do you want to take a look? 
https://github.com/OCA/stock-logistics-barcode/pull/341

We didn't find a better way to work from product.template and product.product. We've tried a computed or related field on product.template but it didn't work as expected.

Thanks!

**Comment by rousseldenis** [comment]
@sebastienbeau What's the status of this ?

**Comment by jjscarafia** [comment]
Hi @sebastienbeau 
I've been working on migrating same module to v13 with some improvements on this pr https://github.com/OCA/stock-logistics-barcode/pull/341
I still need to fix travis. @pedrobaeza suggest to rename the module to product_multi_barcode and I agree.
If we do so on v13 maybe this PR should be re-started from v13 one. What do you think? Do you want me to continue with the changes in v13? any other review to that PR?

Thanks!

**Comment by kevinkhao** [comment]
> Hi @sebastienbeau
> I've been working on migrating same module to v13 with some improvements on this pr #341
> I still need to fix travis. @pedrobaeza suggest to rename the module to product_multi_barcode and I agree.
> If we do so on v13 maybe this PR should be re-started from v13 one. What do you think? Do you want me to continue with the changes in v13? any other review to that PR?
> 
> Thanks!

Hi @jjscarafia we already did a rename https://github.com/akretion/stock-logistics-barcode/pull/11 it is pending though but should be resolved soon

**Comment by kevinkhao** [comment]
@jjscarafia merged now, you can cherry-pick if it LGTY

**Comment by jjscarafia** [comment]
thanks @kevinkhao

**Comment by sebastienbeau** [comment]
@jjscarafia I think you improvement is interesting https://github.com/OCA/stock-logistics-barcode/pull/341/commits/896ef0e1a3cf23a40e2ae4109665322459ab582f
Not every customer use variant so it great to have this on the product.template.
Maybe the simpliest thing is to cherry-pick the commit of Kevin for the renaming and adapt it with your last change, then when the PR in V13 is merged we can create a new PR from scratch for the migration in V14 ?

**Comment by jjscarafia** [comment]
thanks for the feedback @sebastienbeau !
I've made the suggested changes on https://github.com/OCA/stock-logistics-barcode/pull/345

**Comment by kevinkhao** [comment]
superseded by https://github.com/OCA/stock-logistics-barcode/pull/353

**Comment by rousseldenis** [comment]
So, @sebastienbeau we can close this ?

**Pull request closed without merging**
