### PR TITLE
[ADD] Picking Lot barcode module

### PR DESCRIPTION
**Pull request by SimoRubi**
This module allows the user to scan a lot name when in the picking form; this behaviour was present in v8 but has been removed in v10.

Please check

### CODE REVIEW

**Comment by SimoRubi** [comment]
Closing this because depends on an enterprise module

**Comment by pedrobaeza** [comment]
I think this can be done without depending on the enteprise module.

**Comment by SimoRubi** [comment]
@pedrobaeza do you mean depending on `stock` and `barcodes`? Then it would be some kind of a substitute for `stock_barcode` module.. Is this allowed?

**Comment by pedrobaeza** [comment]
Yes, why not? The only rule is to not copy enterprise code, but you can put similar features in OCA that you have in Odoo enterprise. The motivation for that is to have an open source alternative and distribute costs another way: more cost at the beginning (due to development) vs a constant lower cost across time (due to enterprise fee).

There are already several examples of features in OCA that overlaps somehow enteprise modules: responsive interface, website form builder, bom versioning, quality control...

**Pull request closed without merging**
