### PR TITLE
12.0 mig barcodes generator product

### PR DESCRIPTION
**Pull request by cvinh**
Depends on:

- [x] barcodes_generator_abstract - #200

works out of the box in v12

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
LGTM to me. Code review / no test.
:+1: 
CI should be green, as #200 is merged. (I just restarted runbot and Travis)

**Comment by pedrobaeza** [comment]
A rebase is needed.

**Comment by cvinh** [comment]
> A rebase is needed.
I don't see what's wrong with tests, could you help again here pls ?

**Comment by pedrobaeza** [comment]
Well, the error is in one of the test, that is not getting the expected result. This can be due to a change in the way things are done in core that provokes that no barcode is generated. You have to dug on this for getting the problem, and it's what a migration implies (to adapt things to new version). Maybe the problem is on `abstract` module, but showcased here...

**Comment by cvinh** [comment]
@pedrobaeza ok, everything's green

**Review by bealdav — APPROVED** [review]
Code review only. Thanks

**Comment by pedrobaeza** [comment]
Please squash your migration commits together

**Comment by cvinh** [comment]
> Please squash your migration commits together

ok, but I keep the last one because it's a fix not related to the migration... or do you want me to do a PR for that ?

**Comment by pedrobaeza** [comment]
It's legit to keep as a separate commit if it's not something related to migration and can affect other versions, so cherry-picking gets easier.

**Comment by cvinh** [comment]
ok, I did a PR here for the fix : https://github.com/OCA/stock-logistics-barcode/pull/202

**Pull request merged**
