### PR TITLE
[MIG] barcodes_generator_location: Migration to 14.0

### PR DESCRIPTION
**Pull request by Zar21**
Standard migration to 14.0
Depends on https://github.com/OCA/stock-logistics-barcode/pull/340

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional test LGTM

**Comment by dsolanki-initos** [comment]
it would be nice if we get reviews here.

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by dsolanki-initos** [comment]
@moylop260 Can we merge this?

**Pull request merged**
