### PR TITLE
[ADD] stock_barcodes_gs1_expiry: Manage expiry date and use date from GS1 barcodes

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT18620
!! The last module !! :smile:

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Which TT?

**Comment by sergio-teruel** [comment]
TT18620, initial comment updated

**Review by pedrobaeza — APPROVED** [review]
Thanks for the exhaustive tests

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
